// Generated by delombok at Tue Jun 02 07:45:17 PET 2026
package com.GAKOM_ECOTACNA.ECOTACNA.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "companies", indexes = {@Index(name = "idx_companies_ruc", columnList = "ruc")})
public class Company {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @NotNull
    @Size(min = 11, max = 11, message = "El RUC debe tener exactamente 11 dígitos")
    @Column(unique = true, nullable = false, length = 11)
    private String ruc;
    @NotNull
    @Size(max = 255)
    @Column(name = "business_name", nullable = false)
    private String businessName;
    @NotNull
    @Size(max = 500)
    @Column(nullable = false, length = 500)
    private String address;
    @Enumerated(EnumType.STRING)
    @Column(name = "company_type", nullable = false, length = 30)
    private CompanyType companyType;
    @Enumerated(EnumType.STRING)
    @Column(name = "subscription_status", nullable = false, length = 30)
    private SubscriptionStatus subscriptionStatus;
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
    }

    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }

    @java.lang.SuppressWarnings("all")
    private static SubscriptionStatus $default$subscriptionStatus() {
        return SubscriptionStatus.PENDIENTE;
    }


    @java.lang.SuppressWarnings("all")
    public static class CompanyBuilder {
        @java.lang.SuppressWarnings("all")
        private Long id;
        @java.lang.SuppressWarnings("all")
        private String ruc;
        @java.lang.SuppressWarnings("all")
        private String businessName;
        @java.lang.SuppressWarnings("all")
        private String address;
        @java.lang.SuppressWarnings("all")
        private CompanyType companyType;
        @java.lang.SuppressWarnings("all")
        private boolean subscriptionStatus$set;
        @java.lang.SuppressWarnings("all")
        private SubscriptionStatus subscriptionStatus$value;
        @java.lang.SuppressWarnings("all")
        private LocalDateTime createdAt;
        @java.lang.SuppressWarnings("all")
        private LocalDateTime updatedAt;

        @java.lang.SuppressWarnings("all")
        CompanyBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Company.CompanyBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Company.CompanyBuilder ruc(final String ruc) {
            this.ruc = ruc;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Company.CompanyBuilder businessName(final String businessName) {
            this.businessName = businessName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Company.CompanyBuilder address(final String address) {
            this.address = address;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Company.CompanyBuilder companyType(final CompanyType companyType) {
            this.companyType = companyType;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Company.CompanyBuilder subscriptionStatus(final SubscriptionStatus subscriptionStatus) {
            this.subscriptionStatus$value = subscriptionStatus;
            subscriptionStatus$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Company.CompanyBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Company.CompanyBuilder updatedAt(final LocalDateTime updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public Company build() {
            SubscriptionStatus subscriptionStatus$value = this.subscriptionStatus$value;
            if (!this.subscriptionStatus$set) subscriptionStatus$value = Company.$default$subscriptionStatus();
            return new Company(this.id, this.ruc, this.businessName, this.address, this.companyType, subscriptionStatus$value, this.createdAt, this.updatedAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "Company.CompanyBuilder(id=" + this.id + ", ruc=" + this.ruc + ", businessName=" + this.businessName + ", address=" + this.address + ", companyType=" + this.companyType + ", subscriptionStatus$value=" + this.subscriptionStatus$value + ", createdAt=" + this.createdAt + ", updatedAt=" + this.updatedAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static Company.CompanyBuilder builder() {
        return new Company.CompanyBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getRuc() {
        return this.ruc;
    }

    @java.lang.SuppressWarnings("all")
    public String getBusinessName() {
        return this.businessName;
    }

    @java.lang.SuppressWarnings("all")
    public String getAddress() {
        return this.address;
    }

    @java.lang.SuppressWarnings("all")
    public CompanyType getCompanyType() {
        return this.companyType;
    }

    @java.lang.SuppressWarnings("all")
    public SubscriptionStatus getSubscriptionStatus() {
        return this.subscriptionStatus;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setRuc(final String ruc) {
        this.ruc = ruc;
    }

    @java.lang.SuppressWarnings("all")
    public void setBusinessName(final String businessName) {
        this.businessName = businessName;
    }

    @java.lang.SuppressWarnings("all")
    public void setAddress(final String address) {
        this.address = address;
    }

    @java.lang.SuppressWarnings("all")
    public void setCompanyType(final CompanyType companyType) {
        this.companyType = companyType;
    }

    @java.lang.SuppressWarnings("all")
    public void setSubscriptionStatus(final SubscriptionStatus subscriptionStatus) {
        this.subscriptionStatus = subscriptionStatus;
    }

    @java.lang.SuppressWarnings("all")
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setUpdatedAt(final LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    public Company() {
        this.subscriptionStatus = Company.$default$subscriptionStatus();
    }

    @java.lang.SuppressWarnings("all")
    public Company(final Long id, final String ruc, final String businessName, final String address, final CompanyType companyType, final SubscriptionStatus subscriptionStatus, final LocalDateTime createdAt, final LocalDateTime updatedAt) {
        this.id = id;
        this.ruc = ruc;
        this.businessName = businessName;
        this.address = address;
        this.companyType = companyType;
        this.subscriptionStatus = subscriptionStatus;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
}
