// Generated by delombok at Tue Jun 02 07:45:17 PET 2026
package com.GAKOM_ECOTACNA.ECOTACNA.model;

import jakarta.persistence.*;
import lombok.*;
import java.math.BigDecimal;
import java.time.LocalDateTime;

@Entity
@Table(name = "payments")
public class Payment {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "subscription_id")
    private Subscription subscription;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "company_id", nullable = false)
    private Company company;
    @Column(nullable = false, precision = 10, scale = 2)
    private BigDecimal amount;
    @Column(nullable = false, length = 3)
    private String currency;
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 30)
    private PaymentStatus status;
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 30)
    private PaymentProvider provider;
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 30)
    private PaymentMode mode;
    @Column(name = "provider_payment_id", length = 100)
    private String providerPaymentId;
    @Column(name = "provider_charge_id", length = 100)
    private String providerChargeId;
    @Column(name = "provider_token_id", length = 100)
    private String providerTokenId;
    @Column(length = 255)
    private String description;
    @Column(name = "raw_provider_response", columnDefinition = "TEXT")
    private String rawProviderResponse;
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;
    @Column(name = "confirmed_at")
    private LocalDateTime confirmedAt;

    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
    }

    @java.lang.SuppressWarnings("all")
    private static String $default$currency() {
        return "PEN";
    }


    @java.lang.SuppressWarnings("all")
    public static class PaymentBuilder {
        @java.lang.SuppressWarnings("all")
        private Long id;
        @java.lang.SuppressWarnings("all")
        private Subscription subscription;
        @java.lang.SuppressWarnings("all")
        private Company company;
        @java.lang.SuppressWarnings("all")
        private BigDecimal amount;
        @java.lang.SuppressWarnings("all")
        private boolean currency$set;
        @java.lang.SuppressWarnings("all")
        private String currency$value;
        @java.lang.SuppressWarnings("all")
        private PaymentStatus status;
        @java.lang.SuppressWarnings("all")
        private PaymentProvider provider;
        @java.lang.SuppressWarnings("all")
        private PaymentMode mode;
        @java.lang.SuppressWarnings("all")
        private String providerPaymentId;
        @java.lang.SuppressWarnings("all")
        private String providerChargeId;
        @java.lang.SuppressWarnings("all")
        private String providerTokenId;
        @java.lang.SuppressWarnings("all")
        private String description;
        @java.lang.SuppressWarnings("all")
        private String rawProviderResponse;
        @java.lang.SuppressWarnings("all")
        private LocalDateTime createdAt;
        @java.lang.SuppressWarnings("all")
        private LocalDateTime confirmedAt;

        @java.lang.SuppressWarnings("all")
        PaymentBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Payment.PaymentBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Payment.PaymentBuilder subscription(final Subscription subscription) {
            this.subscription = subscription;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Payment.PaymentBuilder company(final Company company) {
            this.company = company;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Payment.PaymentBuilder amount(final BigDecimal amount) {
            this.amount = amount;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Payment.PaymentBuilder currency(final String currency) {
            this.currency$value = currency;
            currency$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Payment.PaymentBuilder status(final PaymentStatus status) {
            this.status = status;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Payment.PaymentBuilder provider(final PaymentProvider provider) {
            this.provider = provider;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Payment.PaymentBuilder mode(final PaymentMode mode) {
            this.mode = mode;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Payment.PaymentBuilder providerPaymentId(final String providerPaymentId) {
            this.providerPaymentId = providerPaymentId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Payment.PaymentBuilder providerChargeId(final String providerChargeId) {
            this.providerChargeId = providerChargeId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Payment.PaymentBuilder providerTokenId(final String providerTokenId) {
            this.providerTokenId = providerTokenId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Payment.PaymentBuilder description(final String description) {
            this.description = description;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Payment.PaymentBuilder rawProviderResponse(final String rawProviderResponse) {
            this.rawProviderResponse = rawProviderResponse;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Payment.PaymentBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Payment.PaymentBuilder confirmedAt(final LocalDateTime confirmedAt) {
            this.confirmedAt = confirmedAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public Payment build() {
            String currency$value = this.currency$value;
            if (!this.currency$set) currency$value = Payment.$default$currency();
            return new Payment(this.id, this.subscription, this.company, this.amount, currency$value, this.status, this.provider, this.mode, this.providerPaymentId, this.providerChargeId, this.providerTokenId, this.description, this.rawProviderResponse, this.createdAt, this.confirmedAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "Payment.PaymentBuilder(id=" + this.id + ", subscription=" + this.subscription + ", company=" + this.company + ", amount=" + this.amount + ", currency$value=" + this.currency$value + ", status=" + this.status + ", provider=" + this.provider + ", mode=" + this.mode + ", providerPaymentId=" + this.providerPaymentId + ", providerChargeId=" + this.providerChargeId + ", providerTokenId=" + this.providerTokenId + ", description=" + this.description + ", rawProviderResponse=" + this.rawProviderResponse + ", createdAt=" + this.createdAt + ", confirmedAt=" + this.confirmedAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static Payment.PaymentBuilder builder() {
        return new Payment.PaymentBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public Subscription getSubscription() {
        return this.subscription;
    }

    @java.lang.SuppressWarnings("all")
    public Company getCompany() {
        return this.company;
    }

    @java.lang.SuppressWarnings("all")
    public BigDecimal getAmount() {
        return this.amount;
    }

    @java.lang.SuppressWarnings("all")
    public String getCurrency() {
        return this.currency;
    }

    @java.lang.SuppressWarnings("all")
    public PaymentStatus getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    public PaymentProvider getProvider() {
        return this.provider;
    }

    @java.lang.SuppressWarnings("all")
    public PaymentMode getMode() {
        return this.mode;
    }

    @java.lang.SuppressWarnings("all")
    public String getProviderPaymentId() {
        return this.providerPaymentId;
    }

    @java.lang.SuppressWarnings("all")
    public String getProviderChargeId() {
        return this.providerChargeId;
    }

    @java.lang.SuppressWarnings("all")
    public String getProviderTokenId() {
        return this.providerTokenId;
    }

    @java.lang.SuppressWarnings("all")
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    public String getRawProviderResponse() {
        return this.rawProviderResponse;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getConfirmedAt() {
        return this.confirmedAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setSubscription(final Subscription subscription) {
        this.subscription = subscription;
    }

    @java.lang.SuppressWarnings("all")
    public void setCompany(final Company company) {
        this.company = company;
    }

    @java.lang.SuppressWarnings("all")
    public void setAmount(final BigDecimal amount) {
        this.amount = amount;
    }

    @java.lang.SuppressWarnings("all")
    public void setCurrency(final String currency) {
        this.currency = currency;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatus(final PaymentStatus status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    public void setProvider(final PaymentProvider provider) {
        this.provider = provider;
    }

    @java.lang.SuppressWarnings("all")
    public void setMode(final PaymentMode mode) {
        this.mode = mode;
    }

    @java.lang.SuppressWarnings("all")
    public void setProviderPaymentId(final String providerPaymentId) {
        this.providerPaymentId = providerPaymentId;
    }

    @java.lang.SuppressWarnings("all")
    public void setProviderChargeId(final String providerChargeId) {
        this.providerChargeId = providerChargeId;
    }

    @java.lang.SuppressWarnings("all")
    public void setProviderTokenId(final String providerTokenId) {
        this.providerTokenId = providerTokenId;
    }

    @java.lang.SuppressWarnings("all")
    public void setDescription(final String description) {
        this.description = description;
    }

    @java.lang.SuppressWarnings("all")
    public void setRawProviderResponse(final String rawProviderResponse) {
        this.rawProviderResponse = rawProviderResponse;
    }

    @java.lang.SuppressWarnings("all")
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setConfirmedAt(final LocalDateTime confirmedAt) {
        this.confirmedAt = confirmedAt;
    }

    @java.lang.SuppressWarnings("all")
    public Payment() {
        this.currency = Payment.$default$currency();
    }

    @java.lang.SuppressWarnings("all")
    public Payment(final Long id, final Subscription subscription, final Company company, final BigDecimal amount, final String currency, final PaymentStatus status, final PaymentProvider provider, final PaymentMode mode, final String providerPaymentId, final String providerChargeId, final String providerTokenId, final String description, final String rawProviderResponse, final LocalDateTime createdAt, final LocalDateTime confirmedAt) {
        this.id = id;
        this.subscription = subscription;
        this.company = company;
        this.amount = amount;
        this.currency = currency;
        this.status = status;
        this.provider = provider;
        this.mode = mode;
        this.providerPaymentId = providerPaymentId;
        this.providerChargeId = providerChargeId;
        this.providerTokenId = providerTokenId;
        this.description = description;
        this.rawProviderResponse = rawProviderResponse;
        this.createdAt = createdAt;
        this.confirmedAt = confirmedAt;
    }
}
