// Generated by delombok at Tue Jun 02 07:45:17 PET 2026
package com.GAKOM_ECOTACNA.ECOTACNA.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import lombok.*;
import java.math.BigDecimal;
import java.time.LocalDateTime;

@Entity
@Table(name = "pickup_requests", indexes = {@Index(name = "idx_pickup_requests_status", columnList = "status"), @Index(name = "idx_pickup_requests_company", columnList = "company_id")})
public class PickupRequest {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @NotNull
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "company_id", nullable = false)
    private Company company;
    @NotNull
    @Column(name = "approximate_volume_liters", nullable = false, precision = 12, scale = 2)
    private BigDecimal approximateVolumeLiters;
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 30)
    private PickupRequestStatus status;
    @Column(name = "requested_at", nullable = false, updatable = false)
    private LocalDateTime requestedAt;
    @Column(name = "scheduled_at")
    private LocalDateTime scheduledAt;
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;
    @Column(name = "collector_user_id")
    private Long collectorUserId;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "transport_unit_id")
    private TransportUnit transportUnit;
    @Column(name = "actual_volume_liters", precision = 12, scale = 2)
    private BigDecimal actualVolumeLiters;
    @Column(name = "collected_at")
    private LocalDateTime collectedAt;
    @Column(columnDefinition = "TEXT")
    private String direccion;
    @Column(columnDefinition = "TEXT")
    private String observaciones;

    @PrePersist
    protected void onCreate() {
        LocalDateTime now = LocalDateTime.now();
        this.requestedAt = now;
        this.updatedAt = now;
    }

    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }

    @java.lang.SuppressWarnings("all")
    private static PickupRequestStatus $default$status() {
        return PickupRequestStatus.PENDIENTE;
    }


    @java.lang.SuppressWarnings("all")
    public static class PickupRequestBuilder {
        @java.lang.SuppressWarnings("all")
        private Long id;
        @java.lang.SuppressWarnings("all")
        private Company company;
        @java.lang.SuppressWarnings("all")
        private BigDecimal approximateVolumeLiters;
        @java.lang.SuppressWarnings("all")
        private boolean status$set;
        @java.lang.SuppressWarnings("all")
        private PickupRequestStatus status$value;
        @java.lang.SuppressWarnings("all")
        private LocalDateTime requestedAt;
        @java.lang.SuppressWarnings("all")
        private LocalDateTime scheduledAt;
        @java.lang.SuppressWarnings("all")
        private LocalDateTime updatedAt;
        @java.lang.SuppressWarnings("all")
        private Long collectorUserId;
        @java.lang.SuppressWarnings("all")
        private TransportUnit transportUnit;
        @java.lang.SuppressWarnings("all")
        private BigDecimal actualVolumeLiters;
        @java.lang.SuppressWarnings("all")
        private LocalDateTime collectedAt;
        @java.lang.SuppressWarnings("all")
        private String direccion;
        @java.lang.SuppressWarnings("all")
        private String observaciones;

        @java.lang.SuppressWarnings("all")
        PickupRequestBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PickupRequest.PickupRequestBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PickupRequest.PickupRequestBuilder company(final Company company) {
            this.company = company;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PickupRequest.PickupRequestBuilder approximateVolumeLiters(final BigDecimal approximateVolumeLiters) {
            this.approximateVolumeLiters = approximateVolumeLiters;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PickupRequest.PickupRequestBuilder status(final PickupRequestStatus status) {
            this.status$value = status;
            status$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PickupRequest.PickupRequestBuilder requestedAt(final LocalDateTime requestedAt) {
            this.requestedAt = requestedAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PickupRequest.PickupRequestBuilder scheduledAt(final LocalDateTime scheduledAt) {
            this.scheduledAt = scheduledAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PickupRequest.PickupRequestBuilder updatedAt(final LocalDateTime updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PickupRequest.PickupRequestBuilder collectorUserId(final Long collectorUserId) {
            this.collectorUserId = collectorUserId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PickupRequest.PickupRequestBuilder transportUnit(final TransportUnit transportUnit) {
            this.transportUnit = transportUnit;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PickupRequest.PickupRequestBuilder actualVolumeLiters(final BigDecimal actualVolumeLiters) {
            this.actualVolumeLiters = actualVolumeLiters;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PickupRequest.PickupRequestBuilder collectedAt(final LocalDateTime collectedAt) {
            this.collectedAt = collectedAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PickupRequest.PickupRequestBuilder direccion(final String direccion) {
            this.direccion = direccion;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PickupRequest.PickupRequestBuilder observaciones(final String observaciones) {
            this.observaciones = observaciones;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public PickupRequest build() {
            PickupRequestStatus status$value = this.status$value;
            if (!this.status$set) status$value = PickupRequest.$default$status();
            return new PickupRequest(this.id, this.company, this.approximateVolumeLiters, status$value, this.requestedAt, this.scheduledAt, this.updatedAt, this.collectorUserId, this.transportUnit, this.actualVolumeLiters, this.collectedAt, this.direccion, this.observaciones);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "PickupRequest.PickupRequestBuilder(id=" + this.id + ", company=" + this.company + ", approximateVolumeLiters=" + this.approximateVolumeLiters + ", status$value=" + this.status$value + ", requestedAt=" + this.requestedAt + ", scheduledAt=" + this.scheduledAt + ", updatedAt=" + this.updatedAt + ", collectorUserId=" + this.collectorUserId + ", transportUnit=" + this.transportUnit + ", actualVolumeLiters=" + this.actualVolumeLiters + ", collectedAt=" + this.collectedAt + ", direccion=" + this.direccion + ", observaciones=" + this.observaciones + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static PickupRequest.PickupRequestBuilder builder() {
        return new PickupRequest.PickupRequestBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public Company getCompany() {
        return this.company;
    }

    @java.lang.SuppressWarnings("all")
    public BigDecimal getApproximateVolumeLiters() {
        return this.approximateVolumeLiters;
    }

    @java.lang.SuppressWarnings("all")
    public PickupRequestStatus getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getRequestedAt() {
        return this.requestedAt;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getScheduledAt() {
        return this.scheduledAt;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    public Long getCollectorUserId() {
        return this.collectorUserId;
    }

    @java.lang.SuppressWarnings("all")
    public TransportUnit getTransportUnit() {
        return this.transportUnit;
    }

    @java.lang.SuppressWarnings("all")
    public BigDecimal getActualVolumeLiters() {
        return this.actualVolumeLiters;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getCollectedAt() {
        return this.collectedAt;
    }

    @java.lang.SuppressWarnings("all")
    public String getDireccion() {
        return this.direccion;
    }

    @java.lang.SuppressWarnings("all")
    public String getObservaciones() {
        return this.observaciones;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setCompany(final Company company) {
        this.company = company;
    }

    @java.lang.SuppressWarnings("all")
    public void setApproximateVolumeLiters(final BigDecimal approximateVolumeLiters) {
        this.approximateVolumeLiters = approximateVolumeLiters;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatus(final PickupRequestStatus status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    public void setRequestedAt(final LocalDateTime requestedAt) {
        this.requestedAt = requestedAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setScheduledAt(final LocalDateTime scheduledAt) {
        this.scheduledAt = scheduledAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setUpdatedAt(final LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setCollectorUserId(final Long collectorUserId) {
        this.collectorUserId = collectorUserId;
    }

    @java.lang.SuppressWarnings("all")
    public void setTransportUnit(final TransportUnit transportUnit) {
        this.transportUnit = transportUnit;
    }

    @java.lang.SuppressWarnings("all")
    public void setActualVolumeLiters(final BigDecimal actualVolumeLiters) {
        this.actualVolumeLiters = actualVolumeLiters;
    }

    @java.lang.SuppressWarnings("all")
    public void setCollectedAt(final LocalDateTime collectedAt) {
        this.collectedAt = collectedAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setDireccion(final String direccion) {
        this.direccion = direccion;
    }

    @java.lang.SuppressWarnings("all")
    public void setObservaciones(final String observaciones) {
        this.observaciones = observaciones;
    }

    @java.lang.SuppressWarnings("all")
    public PickupRequest() {
        this.status = PickupRequest.$default$status();
    }

    @java.lang.SuppressWarnings("all")
    public PickupRequest(final Long id, final Company company, final BigDecimal approximateVolumeLiters, final PickupRequestStatus status, final LocalDateTime requestedAt, final LocalDateTime scheduledAt, final LocalDateTime updatedAt, final Long collectorUserId, final TransportUnit transportUnit, final BigDecimal actualVolumeLiters, final LocalDateTime collectedAt, final String direccion, final String observaciones) {
        this.id = id;
        this.company = company;
        this.approximateVolumeLiters = approximateVolumeLiters;
        this.status = status;
        this.requestedAt = requestedAt;
        this.scheduledAt = scheduledAt;
        this.updatedAt = updatedAt;
        this.collectorUserId = collectorUserId;
        this.transportUnit = transportUnit;
        this.actualVolumeLiters = actualVolumeLiters;
        this.collectedAt = collectedAt;
        this.direccion = direccion;
        this.observaciones = observaciones;
    }
}
