// Generated by delombok at Tue Jun 02 07:45:17 PET 2026
package com.GAKOM_ECOTACNA.ECOTACNA.model;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDate;
import java.time.LocalDateTime;

@Entity
@Table(name = "subscriptions")
public class Subscription {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "company_id", nullable = false)
    private Company company;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "plan_id", nullable = false)
    private SubscriptionPlan plan;
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 30)
    private SubscriptionStatus status;
    @Column(name = "start_date")
    private LocalDate startDate;
    @Column(name = "trial_ends_at")
    private LocalDate trialEndsAt;
    @Column(name = "current_period_start")
    private LocalDate currentPeriodStart;
    @Column(name = "current_period_end")
    private LocalDate currentPeriodEnd;
    @Column(name = "next_billing_date")
    private LocalDate nextBillingDate;
    @Column(length = 50)
    private String provider;
    @Column(name = "provider_customer_id", length = 100)
    private String providerCustomerId;
    @Column(name = "provider_card_id", length = 100)
    private String providerCardId;
    @Column(name = "provider_subscription_id", length = 100)
    private String providerSubscriptionId;
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
    }

    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }


    @java.lang.SuppressWarnings("all")
    public static class SubscriptionBuilder {
        @java.lang.SuppressWarnings("all")
        private Long id;
        @java.lang.SuppressWarnings("all")
        private Company company;
        @java.lang.SuppressWarnings("all")
        private SubscriptionPlan plan;
        @java.lang.SuppressWarnings("all")
        private SubscriptionStatus status;
        @java.lang.SuppressWarnings("all")
        private LocalDate startDate;
        @java.lang.SuppressWarnings("all")
        private LocalDate trialEndsAt;
        @java.lang.SuppressWarnings("all")
        private LocalDate currentPeriodStart;
        @java.lang.SuppressWarnings("all")
        private LocalDate currentPeriodEnd;
        @java.lang.SuppressWarnings("all")
        private LocalDate nextBillingDate;
        @java.lang.SuppressWarnings("all")
        private String provider;
        @java.lang.SuppressWarnings("all")
        private String providerCustomerId;
        @java.lang.SuppressWarnings("all")
        private String providerCardId;
        @java.lang.SuppressWarnings("all")
        private String providerSubscriptionId;
        @java.lang.SuppressWarnings("all")
        private LocalDateTime createdAt;
        @java.lang.SuppressWarnings("all")
        private LocalDateTime updatedAt;

        @java.lang.SuppressWarnings("all")
        SubscriptionBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Subscription.SubscriptionBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Subscription.SubscriptionBuilder company(final Company company) {
            this.company = company;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Subscription.SubscriptionBuilder plan(final SubscriptionPlan plan) {
            this.plan = plan;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Subscription.SubscriptionBuilder status(final SubscriptionStatus status) {
            this.status = status;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Subscription.SubscriptionBuilder startDate(final LocalDate startDate) {
            this.startDate = startDate;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Subscription.SubscriptionBuilder trialEndsAt(final LocalDate trialEndsAt) {
            this.trialEndsAt = trialEndsAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Subscription.SubscriptionBuilder currentPeriodStart(final LocalDate currentPeriodStart) {
            this.currentPeriodStart = currentPeriodStart;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Subscription.SubscriptionBuilder currentPeriodEnd(final LocalDate currentPeriodEnd) {
            this.currentPeriodEnd = currentPeriodEnd;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Subscription.SubscriptionBuilder nextBillingDate(final LocalDate nextBillingDate) {
            this.nextBillingDate = nextBillingDate;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Subscription.SubscriptionBuilder provider(final String provider) {
            this.provider = provider;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Subscription.SubscriptionBuilder providerCustomerId(final String providerCustomerId) {
            this.providerCustomerId = providerCustomerId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Subscription.SubscriptionBuilder providerCardId(final String providerCardId) {
            this.providerCardId = providerCardId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Subscription.SubscriptionBuilder providerSubscriptionId(final String providerSubscriptionId) {
            this.providerSubscriptionId = providerSubscriptionId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Subscription.SubscriptionBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Subscription.SubscriptionBuilder updatedAt(final LocalDateTime updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public Subscription build() {
            return new Subscription(this.id, this.company, this.plan, this.status, this.startDate, this.trialEndsAt, this.currentPeriodStart, this.currentPeriodEnd, this.nextBillingDate, this.provider, this.providerCustomerId, this.providerCardId, this.providerSubscriptionId, this.createdAt, this.updatedAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "Subscription.SubscriptionBuilder(id=" + this.id + ", company=" + this.company + ", plan=" + this.plan + ", status=" + this.status + ", startDate=" + this.startDate + ", trialEndsAt=" + this.trialEndsAt + ", currentPeriodStart=" + this.currentPeriodStart + ", currentPeriodEnd=" + this.currentPeriodEnd + ", nextBillingDate=" + this.nextBillingDate + ", provider=" + this.provider + ", providerCustomerId=" + this.providerCustomerId + ", providerCardId=" + this.providerCardId + ", providerSubscriptionId=" + this.providerSubscriptionId + ", createdAt=" + this.createdAt + ", updatedAt=" + this.updatedAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static Subscription.SubscriptionBuilder builder() {
        return new Subscription.SubscriptionBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public Company getCompany() {
        return this.company;
    }

    @java.lang.SuppressWarnings("all")
    public SubscriptionPlan getPlan() {
        return this.plan;
    }

    @java.lang.SuppressWarnings("all")
    public SubscriptionStatus getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDate getStartDate() {
        return this.startDate;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDate getTrialEndsAt() {
        return this.trialEndsAt;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDate getCurrentPeriodStart() {
        return this.currentPeriodStart;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDate getCurrentPeriodEnd() {
        return this.currentPeriodEnd;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDate getNextBillingDate() {
        return this.nextBillingDate;
    }

    @java.lang.SuppressWarnings("all")
    public String getProvider() {
        return this.provider;
    }

    @java.lang.SuppressWarnings("all")
    public String getProviderCustomerId() {
        return this.providerCustomerId;
    }

    @java.lang.SuppressWarnings("all")
    public String getProviderCardId() {
        return this.providerCardId;
    }

    @java.lang.SuppressWarnings("all")
    public String getProviderSubscriptionId() {
        return this.providerSubscriptionId;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setCompany(final Company company) {
        this.company = company;
    }

    @java.lang.SuppressWarnings("all")
    public void setPlan(final SubscriptionPlan plan) {
        this.plan = plan;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatus(final SubscriptionStatus status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    public void setStartDate(final LocalDate startDate) {
        this.startDate = startDate;
    }

    @java.lang.SuppressWarnings("all")
    public void setTrialEndsAt(final LocalDate trialEndsAt) {
        this.trialEndsAt = trialEndsAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setCurrentPeriodStart(final LocalDate currentPeriodStart) {
        this.currentPeriodStart = currentPeriodStart;
    }

    @java.lang.SuppressWarnings("all")
    public void setCurrentPeriodEnd(final LocalDate currentPeriodEnd) {
        this.currentPeriodEnd = currentPeriodEnd;
    }

    @java.lang.SuppressWarnings("all")
    public void setNextBillingDate(final LocalDate nextBillingDate) {
        this.nextBillingDate = nextBillingDate;
    }

    @java.lang.SuppressWarnings("all")
    public void setProvider(final String provider) {
        this.provider = provider;
    }

    @java.lang.SuppressWarnings("all")
    public void setProviderCustomerId(final String providerCustomerId) {
        this.providerCustomerId = providerCustomerId;
    }

    @java.lang.SuppressWarnings("all")
    public void setProviderCardId(final String providerCardId) {
        this.providerCardId = providerCardId;
    }

    @java.lang.SuppressWarnings("all")
    public void setProviderSubscriptionId(final String providerSubscriptionId) {
        this.providerSubscriptionId = providerSubscriptionId;
    }

    @java.lang.SuppressWarnings("all")
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setUpdatedAt(final LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    public Subscription() {
    }

    @java.lang.SuppressWarnings("all")
    public Subscription(final Long id, final Company company, final SubscriptionPlan plan, final SubscriptionStatus status, final LocalDate startDate, final LocalDate trialEndsAt, final LocalDate currentPeriodStart, final LocalDate currentPeriodEnd, final LocalDate nextBillingDate, final String provider, final String providerCustomerId, final String providerCardId, final String providerSubscriptionId, final LocalDateTime createdAt, final LocalDateTime updatedAt) {
        this.id = id;
        this.company = company;
        this.plan = plan;
        this.status = status;
        this.startDate = startDate;
        this.trialEndsAt = trialEndsAt;
        this.currentPeriodStart = currentPeriodStart;
        this.currentPeriodEnd = currentPeriodEnd;
        this.nextBillingDate = nextBillingDate;
        this.provider = provider;
        this.providerCustomerId = providerCustomerId;
        this.providerCardId = providerCardId;
        this.providerSubscriptionId = providerSubscriptionId;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
}
