// Generated by delombok at Tue Jun 02 07:45:17 PET 2026
package com.GAKOM_ECOTACNA.ECOTACNA.model;

import jakarta.persistence.*;
import lombok.*;
import java.math.BigDecimal;
import java.time.LocalDateTime;

@Entity
@Table(name = "subscription_plans")
public class SubscriptionPlan {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(nullable = false, unique = true, length = 100)
    private String code;
    @Column(nullable = false, length = 200)
    private String name;
    @Enumerated(EnumType.STRING)
    @Column(name = "company_type", nullable = false, length = 30)
    private CompanyType companyType;
    @Column(name = "monthly_amount", nullable = false, precision = 10, scale = 2)
    private BigDecimal monthlyAmount;
    @Column(nullable = false, length = 3)
    private String currency;
    @Column(name = "trial_days", nullable = false)
    private Integer trialDays;
    @Column(nullable = false)
    private Boolean active;
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
    }

    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }

    @java.lang.SuppressWarnings("all")
    private static String $default$currency() {
        return "PEN";
    }

    @java.lang.SuppressWarnings("all")
    private static Integer $default$trialDays() {
        return 0;
    }

    @java.lang.SuppressWarnings("all")
    private static Boolean $default$active() {
        return true;
    }


    @java.lang.SuppressWarnings("all")
    public static class SubscriptionPlanBuilder {
        @java.lang.SuppressWarnings("all")
        private Long id;
        @java.lang.SuppressWarnings("all")
        private String code;
        @java.lang.SuppressWarnings("all")
        private String name;
        @java.lang.SuppressWarnings("all")
        private CompanyType companyType;
        @java.lang.SuppressWarnings("all")
        private BigDecimal monthlyAmount;
        @java.lang.SuppressWarnings("all")
        private boolean currency$set;
        @java.lang.SuppressWarnings("all")
        private String currency$value;
        @java.lang.SuppressWarnings("all")
        private boolean trialDays$set;
        @java.lang.SuppressWarnings("all")
        private Integer trialDays$value;
        @java.lang.SuppressWarnings("all")
        private boolean active$set;
        @java.lang.SuppressWarnings("all")
        private Boolean active$value;
        @java.lang.SuppressWarnings("all")
        private LocalDateTime createdAt;
        @java.lang.SuppressWarnings("all")
        private LocalDateTime updatedAt;

        @java.lang.SuppressWarnings("all")
        SubscriptionPlanBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SubscriptionPlan.SubscriptionPlanBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SubscriptionPlan.SubscriptionPlanBuilder code(final String code) {
            this.code = code;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SubscriptionPlan.SubscriptionPlanBuilder name(final String name) {
            this.name = name;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SubscriptionPlan.SubscriptionPlanBuilder companyType(final CompanyType companyType) {
            this.companyType = companyType;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SubscriptionPlan.SubscriptionPlanBuilder monthlyAmount(final BigDecimal monthlyAmount) {
            this.monthlyAmount = monthlyAmount;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SubscriptionPlan.SubscriptionPlanBuilder currency(final String currency) {
            this.currency$value = currency;
            currency$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SubscriptionPlan.SubscriptionPlanBuilder trialDays(final Integer trialDays) {
            this.trialDays$value = trialDays;
            trialDays$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SubscriptionPlan.SubscriptionPlanBuilder active(final Boolean active) {
            this.active$value = active;
            active$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SubscriptionPlan.SubscriptionPlanBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SubscriptionPlan.SubscriptionPlanBuilder updatedAt(final LocalDateTime updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public SubscriptionPlan build() {
            String currency$value = this.currency$value;
            if (!this.currency$set) currency$value = SubscriptionPlan.$default$currency();
            Integer trialDays$value = this.trialDays$value;
            if (!this.trialDays$set) trialDays$value = SubscriptionPlan.$default$trialDays();
            Boolean active$value = this.active$value;
            if (!this.active$set) active$value = SubscriptionPlan.$default$active();
            return new SubscriptionPlan(this.id, this.code, this.name, this.companyType, this.monthlyAmount, currency$value, trialDays$value, active$value, this.createdAt, this.updatedAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "SubscriptionPlan.SubscriptionPlanBuilder(id=" + this.id + ", code=" + this.code + ", name=" + this.name + ", companyType=" + this.companyType + ", monthlyAmount=" + this.monthlyAmount + ", currency$value=" + this.currency$value + ", trialDays$value=" + this.trialDays$value + ", active$value=" + this.active$value + ", createdAt=" + this.createdAt + ", updatedAt=" + this.updatedAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static SubscriptionPlan.SubscriptionPlanBuilder builder() {
        return new SubscriptionPlan.SubscriptionPlanBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getCode() {
        return this.code;
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public CompanyType getCompanyType() {
        return this.companyType;
    }

    @java.lang.SuppressWarnings("all")
    public BigDecimal getMonthlyAmount() {
        return this.monthlyAmount;
    }

    @java.lang.SuppressWarnings("all")
    public String getCurrency() {
        return this.currency;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getTrialDays() {
        return this.trialDays;
    }

    @java.lang.SuppressWarnings("all")
    public Boolean getActive() {
        return this.active;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setCode(final String code) {
        this.code = code;
    }

    @java.lang.SuppressWarnings("all")
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    public void setCompanyType(final CompanyType companyType) {
        this.companyType = companyType;
    }

    @java.lang.SuppressWarnings("all")
    public void setMonthlyAmount(final BigDecimal monthlyAmount) {
        this.monthlyAmount = monthlyAmount;
    }

    @java.lang.SuppressWarnings("all")
    public void setCurrency(final String currency) {
        this.currency = currency;
    }

    @java.lang.SuppressWarnings("all")
    public void setTrialDays(final Integer trialDays) {
        this.trialDays = trialDays;
    }

    @java.lang.SuppressWarnings("all")
    public void setActive(final Boolean active) {
        this.active = active;
    }

    @java.lang.SuppressWarnings("all")
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setUpdatedAt(final LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    public SubscriptionPlan() {
        this.currency = SubscriptionPlan.$default$currency();
        this.trialDays = SubscriptionPlan.$default$trialDays();
        this.active = SubscriptionPlan.$default$active();
    }

    @java.lang.SuppressWarnings("all")
    public SubscriptionPlan(final Long id, final String code, final String name, final CompanyType companyType, final BigDecimal monthlyAmount, final String currency, final Integer trialDays, final Boolean active, final LocalDateTime createdAt, final LocalDateTime updatedAt) {
        this.id = id;
        this.code = code;
        this.name = name;
        this.companyType = companyType;
        this.monthlyAmount = monthlyAmount;
        this.currency = currency;
        this.trialDays = trialDays;
        this.active = active;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
}
