// Generated by delombok at Tue Jun 02 07:45:17 PET 2026
package com.GAKOM_ECOTACNA.ECOTACNA.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import lombok.*;
import java.math.BigDecimal;
import java.time.LocalDateTime;

@Entity
@Table(name = "transport_units", indexes = {@Index(name = "idx_transport_units_company", columnList = "collector_company_id"), @Index(name = "idx_transport_units_plate", columnList = "plate")})
public class TransportUnit {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @NotNull
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "collector_company_id", nullable = false)
    private Company collectorCompany;
    @NotNull
    @Column(nullable = false, unique = true, length = 12)
    private String plate;
    @Column(length = 60)
    private String brand;
    @Column(length = 60)
    private String model;
    @NotNull
    @Column(name = "capacity_liters", nullable = false, precision = 10, scale = 2)
    private BigDecimal capacityLiters;
    @Column(name = "unit_type", length = 50)
    private String unitType;
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 30)
    private TransportStatus status;
    @Column(columnDefinition = "TEXT")
    private String observations;
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        LocalDateTime now = LocalDateTime.now();
        this.createdAt = now;
        this.updatedAt = now;
        if (this.plate != null) {
            this.plate = this.plate.trim().toUpperCase();
        }
    }

    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = LocalDateTime.now();
        if (this.plate != null) {
            this.plate = this.plate.trim().toUpperCase();
        }
    }

    @java.lang.SuppressWarnings("all")
    private static TransportStatus $default$status() {
        return TransportStatus.ACTIVO;
    }


    @java.lang.SuppressWarnings("all")
    public static class TransportUnitBuilder {
        @java.lang.SuppressWarnings("all")
        private Long id;
        @java.lang.SuppressWarnings("all")
        private Company collectorCompany;
        @java.lang.SuppressWarnings("all")
        private String plate;
        @java.lang.SuppressWarnings("all")
        private String brand;
        @java.lang.SuppressWarnings("all")
        private String model;
        @java.lang.SuppressWarnings("all")
        private BigDecimal capacityLiters;
        @java.lang.SuppressWarnings("all")
        private String unitType;
        @java.lang.SuppressWarnings("all")
        private boolean status$set;
        @java.lang.SuppressWarnings("all")
        private TransportStatus status$value;
        @java.lang.SuppressWarnings("all")
        private String observations;
        @java.lang.SuppressWarnings("all")
        private LocalDateTime createdAt;
        @java.lang.SuppressWarnings("all")
        private LocalDateTime updatedAt;

        @java.lang.SuppressWarnings("all")
        TransportUnitBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public TransportUnit.TransportUnitBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public TransportUnit.TransportUnitBuilder collectorCompany(final Company collectorCompany) {
            this.collectorCompany = collectorCompany;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public TransportUnit.TransportUnitBuilder plate(final String plate) {
            this.plate = plate;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public TransportUnit.TransportUnitBuilder brand(final String brand) {
            this.brand = brand;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public TransportUnit.TransportUnitBuilder model(final String model) {
            this.model = model;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public TransportUnit.TransportUnitBuilder capacityLiters(final BigDecimal capacityLiters) {
            this.capacityLiters = capacityLiters;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public TransportUnit.TransportUnitBuilder unitType(final String unitType) {
            this.unitType = unitType;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public TransportUnit.TransportUnitBuilder status(final TransportStatus status) {
            this.status$value = status;
            status$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public TransportUnit.TransportUnitBuilder observations(final String observations) {
            this.observations = observations;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public TransportUnit.TransportUnitBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public TransportUnit.TransportUnitBuilder updatedAt(final LocalDateTime updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public TransportUnit build() {
            TransportStatus status$value = this.status$value;
            if (!this.status$set) status$value = TransportUnit.$default$status();
            return new TransportUnit(this.id, this.collectorCompany, this.plate, this.brand, this.model, this.capacityLiters, this.unitType, status$value, this.observations, this.createdAt, this.updatedAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "TransportUnit.TransportUnitBuilder(id=" + this.id + ", collectorCompany=" + this.collectorCompany + ", plate=" + this.plate + ", brand=" + this.brand + ", model=" + this.model + ", capacityLiters=" + this.capacityLiters + ", unitType=" + this.unitType + ", status$value=" + this.status$value + ", observations=" + this.observations + ", createdAt=" + this.createdAt + ", updatedAt=" + this.updatedAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static TransportUnit.TransportUnitBuilder builder() {
        return new TransportUnit.TransportUnitBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public Company getCollectorCompany() {
        return this.collectorCompany;
    }

    @java.lang.SuppressWarnings("all")
    public String getPlate() {
        return this.plate;
    }

    @java.lang.SuppressWarnings("all")
    public String getBrand() {
        return this.brand;
    }

    @java.lang.SuppressWarnings("all")
    public String getModel() {
        return this.model;
    }

    @java.lang.SuppressWarnings("all")
    public BigDecimal getCapacityLiters() {
        return this.capacityLiters;
    }

    @java.lang.SuppressWarnings("all")
    public String getUnitType() {
        return this.unitType;
    }

    @java.lang.SuppressWarnings("all")
    public TransportStatus getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    public String getObservations() {
        return this.observations;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setCollectorCompany(final Company collectorCompany) {
        this.collectorCompany = collectorCompany;
    }

    @java.lang.SuppressWarnings("all")
    public void setPlate(final String plate) {
        this.plate = plate;
    }

    @java.lang.SuppressWarnings("all")
    public void setBrand(final String brand) {
        this.brand = brand;
    }

    @java.lang.SuppressWarnings("all")
    public void setModel(final String model) {
        this.model = model;
    }

    @java.lang.SuppressWarnings("all")
    public void setCapacityLiters(final BigDecimal capacityLiters) {
        this.capacityLiters = capacityLiters;
    }

    @java.lang.SuppressWarnings("all")
    public void setUnitType(final String unitType) {
        this.unitType = unitType;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatus(final TransportStatus status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    public void setObservations(final String observations) {
        this.observations = observations;
    }

    @java.lang.SuppressWarnings("all")
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setUpdatedAt(final LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    public TransportUnit() {
        this.status = TransportUnit.$default$status();
    }

    @java.lang.SuppressWarnings("all")
    public TransportUnit(final Long id, final Company collectorCompany, final String plate, final String brand, final String model, final BigDecimal capacityLiters, final String unitType, final TransportStatus status, final String observations, final LocalDateTime createdAt, final LocalDateTime updatedAt) {
        this.id = id;
        this.collectorCompany = collectorCompany;
        this.plate = plate;
        this.brand = brand;
        this.model = model;
        this.capacityLiters = capacityLiters;
        this.unitType = unitType;
        this.status = status;
        this.observations = observations;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
}
