// Generated by delombok at Tue Jun 02 07:45:17 PET 2026
package com.GAKOM_ECOTACNA.ECOTACNA.dto;

import com.GAKOM_ECOTACNA.ECOTACNA.model.SubscriptionStatus;
import jakarta.validation.constraints.NotNull;

public class AdminSubscriptionStatusUpdateRequest {
    @NotNull
    private SubscriptionStatus status;

    @java.lang.SuppressWarnings("all")
    public AdminSubscriptionStatusUpdateRequest() {
    }

    @java.lang.SuppressWarnings("all")
    public SubscriptionStatus getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatus(final SubscriptionStatus status) {
        this.status = status;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof AdminSubscriptionStatusUpdateRequest)) return false;
        final AdminSubscriptionStatusUpdateRequest other = (AdminSubscriptionStatusUpdateRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof AdminSubscriptionStatusUpdateRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "AdminSubscriptionStatusUpdateRequest(status=" + this.getStatus() + ")";
    }
}
