// Generated by delombok at Tue Jun 02 07:45:17 PET 2026
package com.GAKOM_ECOTACNA.ECOTACNA.dto;

import java.math.BigDecimal;

public class CompanySummaryResponse {
    private Long empresaId;
    private String razonSocial;
    private long totalSolicitudes;
    private BigDecimal totalLitrosReciclados;
    private long solicitudesPendientes;
    private long solicitudesCompletadas;

    @java.lang.SuppressWarnings("all")
    public CompanySummaryResponse() {
    }

    @java.lang.SuppressWarnings("all")
    public Long getEmpresaId() {
        return this.empresaId;
    }

    @java.lang.SuppressWarnings("all")
    public String getRazonSocial() {
        return this.razonSocial;
    }

    @java.lang.SuppressWarnings("all")
    public long getTotalSolicitudes() {
        return this.totalSolicitudes;
    }

    @java.lang.SuppressWarnings("all")
    public BigDecimal getTotalLitrosReciclados() {
        return this.totalLitrosReciclados;
    }

    @java.lang.SuppressWarnings("all")
    public long getSolicitudesPendientes() {
        return this.solicitudesPendientes;
    }

    @java.lang.SuppressWarnings("all")
    public long getSolicitudesCompletadas() {
        return this.solicitudesCompletadas;
    }

    @java.lang.SuppressWarnings("all")
    public void setEmpresaId(final Long empresaId) {
        this.empresaId = empresaId;
    }

    @java.lang.SuppressWarnings("all")
    public void setRazonSocial(final String razonSocial) {
        this.razonSocial = razonSocial;
    }

    @java.lang.SuppressWarnings("all")
    public void setTotalSolicitudes(final long totalSolicitudes) {
        this.totalSolicitudes = totalSolicitudes;
    }

    @java.lang.SuppressWarnings("all")
    public void setTotalLitrosReciclados(final BigDecimal totalLitrosReciclados) {
        this.totalLitrosReciclados = totalLitrosReciclados;
    }

    @java.lang.SuppressWarnings("all")
    public void setSolicitudesPendientes(final long solicitudesPendientes) {
        this.solicitudesPendientes = solicitudesPendientes;
    }

    @java.lang.SuppressWarnings("all")
    public void setSolicitudesCompletadas(final long solicitudesCompletadas) {
        this.solicitudesCompletadas = solicitudesCompletadas;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof CompanySummaryResponse)) return false;
        final CompanySummaryResponse other = (CompanySummaryResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.getTotalSolicitudes() != other.getTotalSolicitudes()) return false;
        if (this.getSolicitudesPendientes() != other.getSolicitudesPendientes()) return false;
        if (this.getSolicitudesCompletadas() != other.getSolicitudesCompletadas()) return false;
        final java.lang.Object this$empresaId = this.getEmpresaId();
        final java.lang.Object other$empresaId = other.getEmpresaId();
        if (this$empresaId == null ? other$empresaId != null : !this$empresaId.equals(other$empresaId)) return false;
        final java.lang.Object this$razonSocial = this.getRazonSocial();
        final java.lang.Object other$razonSocial = other.getRazonSocial();
        if (this$razonSocial == null ? other$razonSocial != null : !this$razonSocial.equals(other$razonSocial)) return false;
        final java.lang.Object this$totalLitrosReciclados = this.getTotalLitrosReciclados();
        final java.lang.Object other$totalLitrosReciclados = other.getTotalLitrosReciclados();
        if (this$totalLitrosReciclados == null ? other$totalLitrosReciclados != null : !this$totalLitrosReciclados.equals(other$totalLitrosReciclados)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof CompanySummaryResponse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final long $totalSolicitudes = this.getTotalSolicitudes();
        result = result * PRIME + (int) ($totalSolicitudes >>> 32 ^ $totalSolicitudes);
        final long $solicitudesPendientes = this.getSolicitudesPendientes();
        result = result * PRIME + (int) ($solicitudesPendientes >>> 32 ^ $solicitudesPendientes);
        final long $solicitudesCompletadas = this.getSolicitudesCompletadas();
        result = result * PRIME + (int) ($solicitudesCompletadas >>> 32 ^ $solicitudesCompletadas);
        final java.lang.Object $empresaId = this.getEmpresaId();
        result = result * PRIME + ($empresaId == null ? 43 : $empresaId.hashCode());
        final java.lang.Object $razonSocial = this.getRazonSocial();
        result = result * PRIME + ($razonSocial == null ? 43 : $razonSocial.hashCode());
        final java.lang.Object $totalLitrosReciclados = this.getTotalLitrosReciclados();
        result = result * PRIME + ($totalLitrosReciclados == null ? 43 : $totalLitrosReciclados.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "CompanySummaryResponse(empresaId=" + this.getEmpresaId() + ", razonSocial=" + this.getRazonSocial() + ", totalSolicitudes=" + this.getTotalSolicitudes() + ", totalLitrosReciclados=" + this.getTotalLitrosReciclados() + ", solicitudesPendientes=" + this.getSolicitudesPendientes() + ", solicitudesCompletadas=" + this.getSolicitudesCompletadas() + ")";
    }
}
