// Generated by delombok at Tue Jun 02 07:45:17 PET 2026
package com.GAKOM_ECOTACNA.ECOTACNA.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

public class CulqiPaymentConfirmRequest {
    @NotNull
    private Long paymentId;
    @NotBlank
    private String tokenId;

    @java.lang.SuppressWarnings("all")
    public CulqiPaymentConfirmRequest() {
    }

    @java.lang.SuppressWarnings("all")
    public Long getPaymentId() {
        return this.paymentId;
    }

    @java.lang.SuppressWarnings("all")
    public String getTokenId() {
        return this.tokenId;
    }

    @java.lang.SuppressWarnings("all")
    public void setPaymentId(final Long paymentId) {
        this.paymentId = paymentId;
    }

    @java.lang.SuppressWarnings("all")
    public void setTokenId(final String tokenId) {
        this.tokenId = tokenId;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof CulqiPaymentConfirmRequest)) return false;
        final CulqiPaymentConfirmRequest other = (CulqiPaymentConfirmRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$paymentId = this.getPaymentId();
        final java.lang.Object other$paymentId = other.getPaymentId();
        if (this$paymentId == null ? other$paymentId != null : !this$paymentId.equals(other$paymentId)) return false;
        final java.lang.Object this$tokenId = this.getTokenId();
        final java.lang.Object other$tokenId = other.getTokenId();
        if (this$tokenId == null ? other$tokenId != null : !this$tokenId.equals(other$tokenId)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof CulqiPaymentConfirmRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $paymentId = this.getPaymentId();
        result = result * PRIME + ($paymentId == null ? 43 : $paymentId.hashCode());
        final java.lang.Object $tokenId = this.getTokenId();
        result = result * PRIME + ($tokenId == null ? 43 : $tokenId.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "CulqiPaymentConfirmRequest(paymentId=" + this.getPaymentId() + ", tokenId=" + this.getTokenId() + ")";
    }
}
