// Generated by delombok at Tue Jun 02 07:45:17 PET 2026
package com.GAKOM_ECOTACNA.ECOTACNA.dto;

import jakarta.validation.constraints.NotNull;

public class MockPaymentRequest {
    @NotNull
    private Long paymentId;
    private boolean simulateApproval = true;

    @java.lang.SuppressWarnings("all")
    public MockPaymentRequest() {
    }

    @java.lang.SuppressWarnings("all")
    public Long getPaymentId() {
        return this.paymentId;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isSimulateApproval() {
        return this.simulateApproval;
    }

    @java.lang.SuppressWarnings("all")
    public void setPaymentId(final Long paymentId) {
        this.paymentId = paymentId;
    }

    @java.lang.SuppressWarnings("all")
    public void setSimulateApproval(final boolean simulateApproval) {
        this.simulateApproval = simulateApproval;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof MockPaymentRequest)) return false;
        final MockPaymentRequest other = (MockPaymentRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.isSimulateApproval() != other.isSimulateApproval()) return false;
        final java.lang.Object this$paymentId = this.getPaymentId();
        final java.lang.Object other$paymentId = other.getPaymentId();
        if (this$paymentId == null ? other$paymentId != null : !this$paymentId.equals(other$paymentId)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof MockPaymentRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + (this.isSimulateApproval() ? 79 : 97);
        final java.lang.Object $paymentId = this.getPaymentId();
        result = result * PRIME + ($paymentId == null ? 43 : $paymentId.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "MockPaymentRequest(paymentId=" + this.getPaymentId() + ", simulateApproval=" + this.isSimulateApproval() + ")";
    }
}
