// Generated by delombok at Tue Jun 02 07:45:17 PET 2026
package com.GAKOM_ECOTACNA.ECOTACNA.dto;

import java.math.BigDecimal;

public class PaymentInitResponse {
    private Long paymentId;
    private BigDecimal amount;
    private String currency;
    private String status;
    private String providerPaymentId; // e.g., Culqi order/charge id if generated

    @java.lang.SuppressWarnings("all")
    PaymentInitResponse(final Long paymentId, final BigDecimal amount, final String currency, final String status, final String providerPaymentId) {
        this.paymentId = paymentId;
        this.amount = amount;
        this.currency = currency;
        this.status = status;
        this.providerPaymentId = providerPaymentId;
    }


    @java.lang.SuppressWarnings("all")
    public static class PaymentInitResponseBuilder {
        @java.lang.SuppressWarnings("all")
        private Long paymentId;
        @java.lang.SuppressWarnings("all")
        private BigDecimal amount;
        @java.lang.SuppressWarnings("all")
        private String currency;
        @java.lang.SuppressWarnings("all")
        private String status;
        @java.lang.SuppressWarnings("all")
        private String providerPaymentId;

        @java.lang.SuppressWarnings("all")
        PaymentInitResponseBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PaymentInitResponse.PaymentInitResponseBuilder paymentId(final Long paymentId) {
            this.paymentId = paymentId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PaymentInitResponse.PaymentInitResponseBuilder amount(final BigDecimal amount) {
            this.amount = amount;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PaymentInitResponse.PaymentInitResponseBuilder currency(final String currency) {
            this.currency = currency;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PaymentInitResponse.PaymentInitResponseBuilder status(final String status) {
            this.status = status;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PaymentInitResponse.PaymentInitResponseBuilder providerPaymentId(final String providerPaymentId) {
            this.providerPaymentId = providerPaymentId;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public PaymentInitResponse build() {
            return new PaymentInitResponse(this.paymentId, this.amount, this.currency, this.status, this.providerPaymentId);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "PaymentInitResponse.PaymentInitResponseBuilder(paymentId=" + this.paymentId + ", amount=" + this.amount + ", currency=" + this.currency + ", status=" + this.status + ", providerPaymentId=" + this.providerPaymentId + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static PaymentInitResponse.PaymentInitResponseBuilder builder() {
        return new PaymentInitResponse.PaymentInitResponseBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public Long getPaymentId() {
        return this.paymentId;
    }

    @java.lang.SuppressWarnings("all")
    public BigDecimal getAmount() {
        return this.amount;
    }

    @java.lang.SuppressWarnings("all")
    public String getCurrency() {
        return this.currency;
    }

    @java.lang.SuppressWarnings("all")
    public String getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    public String getProviderPaymentId() {
        return this.providerPaymentId;
    }

    @java.lang.SuppressWarnings("all")
    public void setPaymentId(final Long paymentId) {
        this.paymentId = paymentId;
    }

    @java.lang.SuppressWarnings("all")
    public void setAmount(final BigDecimal amount) {
        this.amount = amount;
    }

    @java.lang.SuppressWarnings("all")
    public void setCurrency(final String currency) {
        this.currency = currency;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatus(final String status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    public void setProviderPaymentId(final String providerPaymentId) {
        this.providerPaymentId = providerPaymentId;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof PaymentInitResponse)) return false;
        final PaymentInitResponse other = (PaymentInitResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$paymentId = this.getPaymentId();
        final java.lang.Object other$paymentId = other.getPaymentId();
        if (this$paymentId == null ? other$paymentId != null : !this$paymentId.equals(other$paymentId)) return false;
        final java.lang.Object this$amount = this.getAmount();
        final java.lang.Object other$amount = other.getAmount();
        if (this$amount == null ? other$amount != null : !this$amount.equals(other$amount)) return false;
        final java.lang.Object this$currency = this.getCurrency();
        final java.lang.Object other$currency = other.getCurrency();
        if (this$currency == null ? other$currency != null : !this$currency.equals(other$currency)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$providerPaymentId = this.getProviderPaymentId();
        final java.lang.Object other$providerPaymentId = other.getProviderPaymentId();
        if (this$providerPaymentId == null ? other$providerPaymentId != null : !this$providerPaymentId.equals(other$providerPaymentId)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof PaymentInitResponse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $paymentId = this.getPaymentId();
        result = result * PRIME + ($paymentId == null ? 43 : $paymentId.hashCode());
        final java.lang.Object $amount = this.getAmount();
        result = result * PRIME + ($amount == null ? 43 : $amount.hashCode());
        final java.lang.Object $currency = this.getCurrency();
        result = result * PRIME + ($currency == null ? 43 : $currency.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $providerPaymentId = this.getProviderPaymentId();
        result = result * PRIME + ($providerPaymentId == null ? 43 : $providerPaymentId.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "PaymentInitResponse(paymentId=" + this.getPaymentId() + ", amount=" + this.getAmount() + ", currency=" + this.getCurrency() + ", status=" + this.getStatus() + ", providerPaymentId=" + this.getProviderPaymentId() + ")";
    }
}
