// Generated by delombok at Tue Jun 02 07:45:17 PET 2026
package com.GAKOM_ECOTACNA.ECOTACNA.dto;

import java.math.BigDecimal;
import java.time.LocalDateTime;

public class PickupRequestResponse {
    private Long id;
    private Long empresaId;
    private String empresaRazonSocial;
    private BigDecimal volumenAproximado;
    private BigDecimal volumenReal;
    private String estado;
    private LocalDateTime fechaSolicitud;
    private LocalDateTime fechaProgramada;
    private LocalDateTime fechaRecoleccion;
    private String transportePlaca;
    private String recolectorAsignado;
    private String direccion;
    private String observaciones;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    @java.lang.SuppressWarnings("all")
    public PickupRequestResponse() {
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public Long getEmpresaId() {
        return this.empresaId;
    }

    @java.lang.SuppressWarnings("all")
    public String getEmpresaRazonSocial() {
        return this.empresaRazonSocial;
    }

    @java.lang.SuppressWarnings("all")
    public BigDecimal getVolumenAproximado() {
        return this.volumenAproximado;
    }

    @java.lang.SuppressWarnings("all")
    public BigDecimal getVolumenReal() {
        return this.volumenReal;
    }

    @java.lang.SuppressWarnings("all")
    public String getEstado() {
        return this.estado;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getFechaSolicitud() {
        return this.fechaSolicitud;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getFechaProgramada() {
        return this.fechaProgramada;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getFechaRecoleccion() {
        return this.fechaRecoleccion;
    }

    @java.lang.SuppressWarnings("all")
    public String getTransportePlaca() {
        return this.transportePlaca;
    }

    @java.lang.SuppressWarnings("all")
    public String getRecolectorAsignado() {
        return this.recolectorAsignado;
    }

    @java.lang.SuppressWarnings("all")
    public String getDireccion() {
        return this.direccion;
    }

    @java.lang.SuppressWarnings("all")
    public String getObservaciones() {
        return this.observaciones;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setEmpresaId(final Long empresaId) {
        this.empresaId = empresaId;
    }

    @java.lang.SuppressWarnings("all")
    public void setEmpresaRazonSocial(final String empresaRazonSocial) {
        this.empresaRazonSocial = empresaRazonSocial;
    }

    @java.lang.SuppressWarnings("all")
    public void setVolumenAproximado(final BigDecimal volumenAproximado) {
        this.volumenAproximado = volumenAproximado;
    }

    @java.lang.SuppressWarnings("all")
    public void setVolumenReal(final BigDecimal volumenReal) {
        this.volumenReal = volumenReal;
    }

    @java.lang.SuppressWarnings("all")
    public void setEstado(final String estado) {
        this.estado = estado;
    }

    @java.lang.SuppressWarnings("all")
    public void setFechaSolicitud(final LocalDateTime fechaSolicitud) {
        this.fechaSolicitud = fechaSolicitud;
    }

    @java.lang.SuppressWarnings("all")
    public void setFechaProgramada(final LocalDateTime fechaProgramada) {
        this.fechaProgramada = fechaProgramada;
    }

    @java.lang.SuppressWarnings("all")
    public void setFechaRecoleccion(final LocalDateTime fechaRecoleccion) {
        this.fechaRecoleccion = fechaRecoleccion;
    }

    @java.lang.SuppressWarnings("all")
    public void setTransportePlaca(final String transportePlaca) {
        this.transportePlaca = transportePlaca;
    }

    @java.lang.SuppressWarnings("all")
    public void setRecolectorAsignado(final String recolectorAsignado) {
        this.recolectorAsignado = recolectorAsignado;
    }

    @java.lang.SuppressWarnings("all")
    public void setDireccion(final String direccion) {
        this.direccion = direccion;
    }

    @java.lang.SuppressWarnings("all")
    public void setObservaciones(final String observaciones) {
        this.observaciones = observaciones;
    }

    @java.lang.SuppressWarnings("all")
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setUpdatedAt(final LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof PickupRequestResponse)) return false;
        final PickupRequestResponse other = (PickupRequestResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$empresaId = this.getEmpresaId();
        final java.lang.Object other$empresaId = other.getEmpresaId();
        if (this$empresaId == null ? other$empresaId != null : !this$empresaId.equals(other$empresaId)) return false;
        final java.lang.Object this$empresaRazonSocial = this.getEmpresaRazonSocial();
        final java.lang.Object other$empresaRazonSocial = other.getEmpresaRazonSocial();
        if (this$empresaRazonSocial == null ? other$empresaRazonSocial != null : !this$empresaRazonSocial.equals(other$empresaRazonSocial)) return false;
        final java.lang.Object this$volumenAproximado = this.getVolumenAproximado();
        final java.lang.Object other$volumenAproximado = other.getVolumenAproximado();
        if (this$volumenAproximado == null ? other$volumenAproximado != null : !this$volumenAproximado.equals(other$volumenAproximado)) return false;
        final java.lang.Object this$volumenReal = this.getVolumenReal();
        final java.lang.Object other$volumenReal = other.getVolumenReal();
        if (this$volumenReal == null ? other$volumenReal != null : !this$volumenReal.equals(other$volumenReal)) return false;
        final java.lang.Object this$estado = this.getEstado();
        final java.lang.Object other$estado = other.getEstado();
        if (this$estado == null ? other$estado != null : !this$estado.equals(other$estado)) return false;
        final java.lang.Object this$fechaSolicitud = this.getFechaSolicitud();
        final java.lang.Object other$fechaSolicitud = other.getFechaSolicitud();
        if (this$fechaSolicitud == null ? other$fechaSolicitud != null : !this$fechaSolicitud.equals(other$fechaSolicitud)) return false;
        final java.lang.Object this$fechaProgramada = this.getFechaProgramada();
        final java.lang.Object other$fechaProgramada = other.getFechaProgramada();
        if (this$fechaProgramada == null ? other$fechaProgramada != null : !this$fechaProgramada.equals(other$fechaProgramada)) return false;
        final java.lang.Object this$fechaRecoleccion = this.getFechaRecoleccion();
        final java.lang.Object other$fechaRecoleccion = other.getFechaRecoleccion();
        if (this$fechaRecoleccion == null ? other$fechaRecoleccion != null : !this$fechaRecoleccion.equals(other$fechaRecoleccion)) return false;
        final java.lang.Object this$transportePlaca = this.getTransportePlaca();
        final java.lang.Object other$transportePlaca = other.getTransportePlaca();
        if (this$transportePlaca == null ? other$transportePlaca != null : !this$transportePlaca.equals(other$transportePlaca)) return false;
        final java.lang.Object this$recolectorAsignado = this.getRecolectorAsignado();
        final java.lang.Object other$recolectorAsignado = other.getRecolectorAsignado();
        if (this$recolectorAsignado == null ? other$recolectorAsignado != null : !this$recolectorAsignado.equals(other$recolectorAsignado)) return false;
        final java.lang.Object this$direccion = this.getDireccion();
        final java.lang.Object other$direccion = other.getDireccion();
        if (this$direccion == null ? other$direccion != null : !this$direccion.equals(other$direccion)) return false;
        final java.lang.Object this$observaciones = this.getObservaciones();
        final java.lang.Object other$observaciones = other.getObservaciones();
        if (this$observaciones == null ? other$observaciones != null : !this$observaciones.equals(other$observaciones)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        final java.lang.Object this$updatedAt = this.getUpdatedAt();
        final java.lang.Object other$updatedAt = other.getUpdatedAt();
        if (this$updatedAt == null ? other$updatedAt != null : !this$updatedAt.equals(other$updatedAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof PickupRequestResponse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $empresaId = this.getEmpresaId();
        result = result * PRIME + ($empresaId == null ? 43 : $empresaId.hashCode());
        final java.lang.Object $empresaRazonSocial = this.getEmpresaRazonSocial();
        result = result * PRIME + ($empresaRazonSocial == null ? 43 : $empresaRazonSocial.hashCode());
        final java.lang.Object $volumenAproximado = this.getVolumenAproximado();
        result = result * PRIME + ($volumenAproximado == null ? 43 : $volumenAproximado.hashCode());
        final java.lang.Object $volumenReal = this.getVolumenReal();
        result = result * PRIME + ($volumenReal == null ? 43 : $volumenReal.hashCode());
        final java.lang.Object $estado = this.getEstado();
        result = result * PRIME + ($estado == null ? 43 : $estado.hashCode());
        final java.lang.Object $fechaSolicitud = this.getFechaSolicitud();
        result = result * PRIME + ($fechaSolicitud == null ? 43 : $fechaSolicitud.hashCode());
        final java.lang.Object $fechaProgramada = this.getFechaProgramada();
        result = result * PRIME + ($fechaProgramada == null ? 43 : $fechaProgramada.hashCode());
        final java.lang.Object $fechaRecoleccion = this.getFechaRecoleccion();
        result = result * PRIME + ($fechaRecoleccion == null ? 43 : $fechaRecoleccion.hashCode());
        final java.lang.Object $transportePlaca = this.getTransportePlaca();
        result = result * PRIME + ($transportePlaca == null ? 43 : $transportePlaca.hashCode());
        final java.lang.Object $recolectorAsignado = this.getRecolectorAsignado();
        result = result * PRIME + ($recolectorAsignado == null ? 43 : $recolectorAsignado.hashCode());
        final java.lang.Object $direccion = this.getDireccion();
        result = result * PRIME + ($direccion == null ? 43 : $direccion.hashCode());
        final java.lang.Object $observaciones = this.getObservaciones();
        result = result * PRIME + ($observaciones == null ? 43 : $observaciones.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        final java.lang.Object $updatedAt = this.getUpdatedAt();
        result = result * PRIME + ($updatedAt == null ? 43 : $updatedAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "PickupRequestResponse(id=" + this.getId() + ", empresaId=" + this.getEmpresaId() + ", empresaRazonSocial=" + this.getEmpresaRazonSocial() + ", volumenAproximado=" + this.getVolumenAproximado() + ", volumenReal=" + this.getVolumenReal() + ", estado=" + this.getEstado() + ", fechaSolicitud=" + this.getFechaSolicitud() + ", fechaProgramada=" + this.getFechaProgramada() + ", fechaRecoleccion=" + this.getFechaRecoleccion() + ", transportePlaca=" + this.getTransportePlaca() + ", recolectorAsignado=" + this.getRecolectorAsignado() + ", direccion=" + this.getDireccion() + ", observaciones=" + this.getObservaciones() + ", createdAt=" + this.getCreatedAt() + ", updatedAt=" + this.getUpdatedAt() + ")";
    }
}
