// Generated by delombok at Tue Jun 02 07:45:17 PET 2026
package com.GAKOM_ECOTACNA.ECOTACNA.dto;

import jakarta.validation.constraints.NotNull;

public class PickupAssignmentRequest {
    @NotNull(message = "recolectorId es obligatorio")
    private Long recolectorId;
    private Long transporteId;

    @java.lang.SuppressWarnings("all")
    public PickupAssignmentRequest() {
    }

    @java.lang.SuppressWarnings("all")
    public Long getRecolectorId() {
        return this.recolectorId;
    }

    @java.lang.SuppressWarnings("all")
    public Long getTransporteId() {
        return this.transporteId;
    }

    @java.lang.SuppressWarnings("all")
    public void setRecolectorId(final Long recolectorId) {
        this.recolectorId = recolectorId;
    }

    @java.lang.SuppressWarnings("all")
    public void setTransporteId(final Long transporteId) {
        this.transporteId = transporteId;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof PickupAssignmentRequest)) return false;
        final PickupAssignmentRequest other = (PickupAssignmentRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$recolectorId = this.getRecolectorId();
        final java.lang.Object other$recolectorId = other.getRecolectorId();
        if (this$recolectorId == null ? other$recolectorId != null : !this$recolectorId.equals(other$recolectorId)) return false;
        final java.lang.Object this$transporteId = this.getTransporteId();
        final java.lang.Object other$transporteId = other.getTransporteId();
        if (this$transporteId == null ? other$transporteId != null : !this$transporteId.equals(other$transporteId)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof PickupAssignmentRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $recolectorId = this.getRecolectorId();
        result = result * PRIME + ($recolectorId == null ? 43 : $recolectorId.hashCode());
        final java.lang.Object $transporteId = this.getTransporteId();
        result = result * PRIME + ($transporteId == null ? 43 : $transporteId.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "PickupAssignmentRequest(recolectorId=" + this.getRecolectorId() + ", transporteId=" + this.getTransporteId() + ")";
    }
}
