// Generated by delombok at Tue Jun 02 07:45:17 PET 2026
package com.GAKOM_ECOTACNA.ECOTACNA.dto;

import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.NotNull;
import java.math.BigDecimal;
import java.time.LocalDateTime;

public class PickupRequestRequest {
    @NotNull(message = "volumenAproximado es obligatorio")
    @DecimalMin(value = "0.01", message = "El volumen aproximado debe ser mayor a 0")
    private BigDecimal volumenAproximado;
    private LocalDateTime fechaProgramada;
    private String direccion;
    private String observaciones;

    @java.lang.SuppressWarnings("all")
    public PickupRequestRequest() {
    }

    @java.lang.SuppressWarnings("all")
    public BigDecimal getVolumenAproximado() {
        return this.volumenAproximado;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getFechaProgramada() {
        return this.fechaProgramada;
    }

    @java.lang.SuppressWarnings("all")
    public String getDireccion() {
        return this.direccion;
    }

    @java.lang.SuppressWarnings("all")
    public String getObservaciones() {
        return this.observaciones;
    }

    @java.lang.SuppressWarnings("all")
    public void setVolumenAproximado(final BigDecimal volumenAproximado) {
        this.volumenAproximado = volumenAproximado;
    }

    @java.lang.SuppressWarnings("all")
    public void setFechaProgramada(final LocalDateTime fechaProgramada) {
        this.fechaProgramada = fechaProgramada;
    }

    @java.lang.SuppressWarnings("all")
    public void setDireccion(final String direccion) {
        this.direccion = direccion;
    }

    @java.lang.SuppressWarnings("all")
    public void setObservaciones(final String observaciones) {
        this.observaciones = observaciones;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof PickupRequestRequest)) return false;
        final PickupRequestRequest other = (PickupRequestRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$volumenAproximado = this.getVolumenAproximado();
        final java.lang.Object other$volumenAproximado = other.getVolumenAproximado();
        if (this$volumenAproximado == null ? other$volumenAproximado != null : !this$volumenAproximado.equals(other$volumenAproximado)) return false;
        final java.lang.Object this$fechaProgramada = this.getFechaProgramada();
        final java.lang.Object other$fechaProgramada = other.getFechaProgramada();
        if (this$fechaProgramada == null ? other$fechaProgramada != null : !this$fechaProgramada.equals(other$fechaProgramada)) return false;
        final java.lang.Object this$direccion = this.getDireccion();
        final java.lang.Object other$direccion = other.getDireccion();
        if (this$direccion == null ? other$direccion != null : !this$direccion.equals(other$direccion)) return false;
        final java.lang.Object this$observaciones = this.getObservaciones();
        final java.lang.Object other$observaciones = other.getObservaciones();
        if (this$observaciones == null ? other$observaciones != null : !this$observaciones.equals(other$observaciones)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof PickupRequestRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $volumenAproximado = this.getVolumenAproximado();
        result = result * PRIME + ($volumenAproximado == null ? 43 : $volumenAproximado.hashCode());
        final java.lang.Object $fechaProgramada = this.getFechaProgramada();
        result = result * PRIME + ($fechaProgramada == null ? 43 : $fechaProgramada.hashCode());
        final java.lang.Object $direccion = this.getDireccion();
        result = result * PRIME + ($direccion == null ? 43 : $direccion.hashCode());
        final java.lang.Object $observaciones = this.getObservaciones();
        result = result * PRIME + ($observaciones == null ? 43 : $observaciones.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "PickupRequestRequest(volumenAproximado=" + this.getVolumenAproximado() + ", fechaProgramada=" + this.getFechaProgramada() + ", direccion=" + this.getDireccion() + ", observaciones=" + this.getObservaciones() + ")";
    }
}
