// Generated by delombok at Tue Jun 02 07:45:17 PET 2026
package com.GAKOM_ECOTACNA.ECOTACNA.dto;

import java.math.BigDecimal;

public class PlanResponse {
    private Long id;
    private String code;
    private String name;
    private String companyType;
    private BigDecimal monthlyAmount;
    private String currency;
    private Integer trialDays;

    @java.lang.SuppressWarnings("all")
    PlanResponse(final Long id, final String code, final String name, final String companyType, final BigDecimal monthlyAmount, final String currency, final Integer trialDays) {
        this.id = id;
        this.code = code;
        this.name = name;
        this.companyType = companyType;
        this.monthlyAmount = monthlyAmount;
        this.currency = currency;
        this.trialDays = trialDays;
    }


    @java.lang.SuppressWarnings("all")
    public static class PlanResponseBuilder {
        @java.lang.SuppressWarnings("all")
        private Long id;
        @java.lang.SuppressWarnings("all")
        private String code;
        @java.lang.SuppressWarnings("all")
        private String name;
        @java.lang.SuppressWarnings("all")
        private String companyType;
        @java.lang.SuppressWarnings("all")
        private BigDecimal monthlyAmount;
        @java.lang.SuppressWarnings("all")
        private String currency;
        @java.lang.SuppressWarnings("all")
        private Integer trialDays;

        @java.lang.SuppressWarnings("all")
        PlanResponseBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PlanResponse.PlanResponseBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PlanResponse.PlanResponseBuilder code(final String code) {
            this.code = code;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PlanResponse.PlanResponseBuilder name(final String name) {
            this.name = name;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PlanResponse.PlanResponseBuilder companyType(final String companyType) {
            this.companyType = companyType;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PlanResponse.PlanResponseBuilder monthlyAmount(final BigDecimal monthlyAmount) {
            this.monthlyAmount = monthlyAmount;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PlanResponse.PlanResponseBuilder currency(final String currency) {
            this.currency = currency;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PlanResponse.PlanResponseBuilder trialDays(final Integer trialDays) {
            this.trialDays = trialDays;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public PlanResponse build() {
            return new PlanResponse(this.id, this.code, this.name, this.companyType, this.monthlyAmount, this.currency, this.trialDays);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "PlanResponse.PlanResponseBuilder(id=" + this.id + ", code=" + this.code + ", name=" + this.name + ", companyType=" + this.companyType + ", monthlyAmount=" + this.monthlyAmount + ", currency=" + this.currency + ", trialDays=" + this.trialDays + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static PlanResponse.PlanResponseBuilder builder() {
        return new PlanResponse.PlanResponseBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getCode() {
        return this.code;
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public String getCompanyType() {
        return this.companyType;
    }

    @java.lang.SuppressWarnings("all")
    public BigDecimal getMonthlyAmount() {
        return this.monthlyAmount;
    }

    @java.lang.SuppressWarnings("all")
    public String getCurrency() {
        return this.currency;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getTrialDays() {
        return this.trialDays;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setCode(final String code) {
        this.code = code;
    }

    @java.lang.SuppressWarnings("all")
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    public void setCompanyType(final String companyType) {
        this.companyType = companyType;
    }

    @java.lang.SuppressWarnings("all")
    public void setMonthlyAmount(final BigDecimal monthlyAmount) {
        this.monthlyAmount = monthlyAmount;
    }

    @java.lang.SuppressWarnings("all")
    public void setCurrency(final String currency) {
        this.currency = currency;
    }

    @java.lang.SuppressWarnings("all")
    public void setTrialDays(final Integer trialDays) {
        this.trialDays = trialDays;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof PlanResponse)) return false;
        final PlanResponse other = (PlanResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$trialDays = this.getTrialDays();
        final java.lang.Object other$trialDays = other.getTrialDays();
        if (this$trialDays == null ? other$trialDays != null : !this$trialDays.equals(other$trialDays)) return false;
        final java.lang.Object this$code = this.getCode();
        final java.lang.Object other$code = other.getCode();
        if (this$code == null ? other$code != null : !this$code.equals(other$code)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$companyType = this.getCompanyType();
        final java.lang.Object other$companyType = other.getCompanyType();
        if (this$companyType == null ? other$companyType != null : !this$companyType.equals(other$companyType)) return false;
        final java.lang.Object this$monthlyAmount = this.getMonthlyAmount();
        final java.lang.Object other$monthlyAmount = other.getMonthlyAmount();
        if (this$monthlyAmount == null ? other$monthlyAmount != null : !this$monthlyAmount.equals(other$monthlyAmount)) return false;
        final java.lang.Object this$currency = this.getCurrency();
        final java.lang.Object other$currency = other.getCurrency();
        if (this$currency == null ? other$currency != null : !this$currency.equals(other$currency)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof PlanResponse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $trialDays = this.getTrialDays();
        result = result * PRIME + ($trialDays == null ? 43 : $trialDays.hashCode());
        final java.lang.Object $code = this.getCode();
        result = result * PRIME + ($code == null ? 43 : $code.hashCode());
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $companyType = this.getCompanyType();
        result = result * PRIME + ($companyType == null ? 43 : $companyType.hashCode());
        final java.lang.Object $monthlyAmount = this.getMonthlyAmount();
        result = result * PRIME + ($monthlyAmount == null ? 43 : $monthlyAmount.hashCode());
        final java.lang.Object $currency = this.getCurrency();
        result = result * PRIME + ($currency == null ? 43 : $currency.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "PlanResponse(id=" + this.getId() + ", code=" + this.getCode() + ", name=" + this.getName() + ", companyType=" + this.getCompanyType() + ", monthlyAmount=" + this.getMonthlyAmount() + ", currency=" + this.getCurrency() + ", trialDays=" + this.getTrialDays() + ")";
    }
}
