// Generated by delombok at Tue Jun 02 07:45:17 PET 2026
package com.GAKOM_ECOTACNA.ECOTACNA.dto;

public class RucLookupResponse {
    private String ruc;
    private String razonSocial;
    private String nombreComercial;
    private String direccionFiscal;
    private String distrito;
    private String provincia;
    private String departamento;
    private String estadoContribuyente;
    private String condicionDomicilio;
    private String fuente;


    @java.lang.SuppressWarnings("all")
    public static class RucLookupResponseBuilder {
        @java.lang.SuppressWarnings("all")
        private String ruc;
        @java.lang.SuppressWarnings("all")
        private String razonSocial;
        @java.lang.SuppressWarnings("all")
        private String nombreComercial;
        @java.lang.SuppressWarnings("all")
        private String direccionFiscal;
        @java.lang.SuppressWarnings("all")
        private String distrito;
        @java.lang.SuppressWarnings("all")
        private String provincia;
        @java.lang.SuppressWarnings("all")
        private String departamento;
        @java.lang.SuppressWarnings("all")
        private String estadoContribuyente;
        @java.lang.SuppressWarnings("all")
        private String condicionDomicilio;
        @java.lang.SuppressWarnings("all")
        private String fuente;

        @java.lang.SuppressWarnings("all")
        RucLookupResponseBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RucLookupResponse.RucLookupResponseBuilder ruc(final String ruc) {
            this.ruc = ruc;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RucLookupResponse.RucLookupResponseBuilder razonSocial(final String razonSocial) {
            this.razonSocial = razonSocial;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RucLookupResponse.RucLookupResponseBuilder nombreComercial(final String nombreComercial) {
            this.nombreComercial = nombreComercial;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RucLookupResponse.RucLookupResponseBuilder direccionFiscal(final String direccionFiscal) {
            this.direccionFiscal = direccionFiscal;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RucLookupResponse.RucLookupResponseBuilder distrito(final String distrito) {
            this.distrito = distrito;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RucLookupResponse.RucLookupResponseBuilder provincia(final String provincia) {
            this.provincia = provincia;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RucLookupResponse.RucLookupResponseBuilder departamento(final String departamento) {
            this.departamento = departamento;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RucLookupResponse.RucLookupResponseBuilder estadoContribuyente(final String estadoContribuyente) {
            this.estadoContribuyente = estadoContribuyente;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RucLookupResponse.RucLookupResponseBuilder condicionDomicilio(final String condicionDomicilio) {
            this.condicionDomicilio = condicionDomicilio;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RucLookupResponse.RucLookupResponseBuilder fuente(final String fuente) {
            this.fuente = fuente;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public RucLookupResponse build() {
            return new RucLookupResponse(this.ruc, this.razonSocial, this.nombreComercial, this.direccionFiscal, this.distrito, this.provincia, this.departamento, this.estadoContribuyente, this.condicionDomicilio, this.fuente);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "RucLookupResponse.RucLookupResponseBuilder(ruc=" + this.ruc + ", razonSocial=" + this.razonSocial + ", nombreComercial=" + this.nombreComercial + ", direccionFiscal=" + this.direccionFiscal + ", distrito=" + this.distrito + ", provincia=" + this.provincia + ", departamento=" + this.departamento + ", estadoContribuyente=" + this.estadoContribuyente + ", condicionDomicilio=" + this.condicionDomicilio + ", fuente=" + this.fuente + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static RucLookupResponse.RucLookupResponseBuilder builder() {
        return new RucLookupResponse.RucLookupResponseBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public String getRuc() {
        return this.ruc;
    }

    @java.lang.SuppressWarnings("all")
    public String getRazonSocial() {
        return this.razonSocial;
    }

    @java.lang.SuppressWarnings("all")
    public String getNombreComercial() {
        return this.nombreComercial;
    }

    @java.lang.SuppressWarnings("all")
    public String getDireccionFiscal() {
        return this.direccionFiscal;
    }

    @java.lang.SuppressWarnings("all")
    public String getDistrito() {
        return this.distrito;
    }

    @java.lang.SuppressWarnings("all")
    public String getProvincia() {
        return this.provincia;
    }

    @java.lang.SuppressWarnings("all")
    public String getDepartamento() {
        return this.departamento;
    }

    @java.lang.SuppressWarnings("all")
    public String getEstadoContribuyente() {
        return this.estadoContribuyente;
    }

    @java.lang.SuppressWarnings("all")
    public String getCondicionDomicilio() {
        return this.condicionDomicilio;
    }

    @java.lang.SuppressWarnings("all")
    public String getFuente() {
        return this.fuente;
    }

    @java.lang.SuppressWarnings("all")
    public void setRuc(final String ruc) {
        this.ruc = ruc;
    }

    @java.lang.SuppressWarnings("all")
    public void setRazonSocial(final String razonSocial) {
        this.razonSocial = razonSocial;
    }

    @java.lang.SuppressWarnings("all")
    public void setNombreComercial(final String nombreComercial) {
        this.nombreComercial = nombreComercial;
    }

    @java.lang.SuppressWarnings("all")
    public void setDireccionFiscal(final String direccionFiscal) {
        this.direccionFiscal = direccionFiscal;
    }

    @java.lang.SuppressWarnings("all")
    public void setDistrito(final String distrito) {
        this.distrito = distrito;
    }

    @java.lang.SuppressWarnings("all")
    public void setProvincia(final String provincia) {
        this.provincia = provincia;
    }

    @java.lang.SuppressWarnings("all")
    public void setDepartamento(final String departamento) {
        this.departamento = departamento;
    }

    @java.lang.SuppressWarnings("all")
    public void setEstadoContribuyente(final String estadoContribuyente) {
        this.estadoContribuyente = estadoContribuyente;
    }

    @java.lang.SuppressWarnings("all")
    public void setCondicionDomicilio(final String condicionDomicilio) {
        this.condicionDomicilio = condicionDomicilio;
    }

    @java.lang.SuppressWarnings("all")
    public void setFuente(final String fuente) {
        this.fuente = fuente;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof RucLookupResponse)) return false;
        final RucLookupResponse other = (RucLookupResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$ruc = this.getRuc();
        final java.lang.Object other$ruc = other.getRuc();
        if (this$ruc == null ? other$ruc != null : !this$ruc.equals(other$ruc)) return false;
        final java.lang.Object this$razonSocial = this.getRazonSocial();
        final java.lang.Object other$razonSocial = other.getRazonSocial();
        if (this$razonSocial == null ? other$razonSocial != null : !this$razonSocial.equals(other$razonSocial)) return false;
        final java.lang.Object this$nombreComercial = this.getNombreComercial();
        final java.lang.Object other$nombreComercial = other.getNombreComercial();
        if (this$nombreComercial == null ? other$nombreComercial != null : !this$nombreComercial.equals(other$nombreComercial)) return false;
        final java.lang.Object this$direccionFiscal = this.getDireccionFiscal();
        final java.lang.Object other$direccionFiscal = other.getDireccionFiscal();
        if (this$direccionFiscal == null ? other$direccionFiscal != null : !this$direccionFiscal.equals(other$direccionFiscal)) return false;
        final java.lang.Object this$distrito = this.getDistrito();
        final java.lang.Object other$distrito = other.getDistrito();
        if (this$distrito == null ? other$distrito != null : !this$distrito.equals(other$distrito)) return false;
        final java.lang.Object this$provincia = this.getProvincia();
        final java.lang.Object other$provincia = other.getProvincia();
        if (this$provincia == null ? other$provincia != null : !this$provincia.equals(other$provincia)) return false;
        final java.lang.Object this$departamento = this.getDepartamento();
        final java.lang.Object other$departamento = other.getDepartamento();
        if (this$departamento == null ? other$departamento != null : !this$departamento.equals(other$departamento)) return false;
        final java.lang.Object this$estadoContribuyente = this.getEstadoContribuyente();
        final java.lang.Object other$estadoContribuyente = other.getEstadoContribuyente();
        if (this$estadoContribuyente == null ? other$estadoContribuyente != null : !this$estadoContribuyente.equals(other$estadoContribuyente)) return false;
        final java.lang.Object this$condicionDomicilio = this.getCondicionDomicilio();
        final java.lang.Object other$condicionDomicilio = other.getCondicionDomicilio();
        if (this$condicionDomicilio == null ? other$condicionDomicilio != null : !this$condicionDomicilio.equals(other$condicionDomicilio)) return false;
        final java.lang.Object this$fuente = this.getFuente();
        final java.lang.Object other$fuente = other.getFuente();
        if (this$fuente == null ? other$fuente != null : !this$fuente.equals(other$fuente)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof RucLookupResponse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $ruc = this.getRuc();
        result = result * PRIME + ($ruc == null ? 43 : $ruc.hashCode());
        final java.lang.Object $razonSocial = this.getRazonSocial();
        result = result * PRIME + ($razonSocial == null ? 43 : $razonSocial.hashCode());
        final java.lang.Object $nombreComercial = this.getNombreComercial();
        result = result * PRIME + ($nombreComercial == null ? 43 : $nombreComercial.hashCode());
        final java.lang.Object $direccionFiscal = this.getDireccionFiscal();
        result = result * PRIME + ($direccionFiscal == null ? 43 : $direccionFiscal.hashCode());
        final java.lang.Object $distrito = this.getDistrito();
        result = result * PRIME + ($distrito == null ? 43 : $distrito.hashCode());
        final java.lang.Object $provincia = this.getProvincia();
        result = result * PRIME + ($provincia == null ? 43 : $provincia.hashCode());
        final java.lang.Object $departamento = this.getDepartamento();
        result = result * PRIME + ($departamento == null ? 43 : $departamento.hashCode());
        final java.lang.Object $estadoContribuyente = this.getEstadoContribuyente();
        result = result * PRIME + ($estadoContribuyente == null ? 43 : $estadoContribuyente.hashCode());
        final java.lang.Object $condicionDomicilio = this.getCondicionDomicilio();
        result = result * PRIME + ($condicionDomicilio == null ? 43 : $condicionDomicilio.hashCode());
        final java.lang.Object $fuente = this.getFuente();
        result = result * PRIME + ($fuente == null ? 43 : $fuente.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "RucLookupResponse(ruc=" + this.getRuc() + ", razonSocial=" + this.getRazonSocial() + ", nombreComercial=" + this.getNombreComercial() + ", direccionFiscal=" + this.getDireccionFiscal() + ", distrito=" + this.getDistrito() + ", provincia=" + this.getProvincia() + ", departamento=" + this.getDepartamento() + ", estadoContribuyente=" + this.getEstadoContribuyente() + ", condicionDomicilio=" + this.getCondicionDomicilio() + ", fuente=" + this.getFuente() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public RucLookupResponse() {
    }

    @java.lang.SuppressWarnings("all")
    public RucLookupResponse(final String ruc, final String razonSocial, final String nombreComercial, final String direccionFiscal, final String distrito, final String provincia, final String departamento, final String estadoContribuyente, final String condicionDomicilio, final String fuente) {
        this.ruc = ruc;
        this.razonSocial = razonSocial;
        this.nombreComercial = nombreComercial;
        this.direccionFiscal = direccionFiscal;
        this.distrito = distrito;
        this.provincia = provincia;
        this.departamento = departamento;
        this.estadoContribuyente = estadoContribuyente;
        this.condicionDomicilio = condicionDomicilio;
        this.fuente = fuente;
    }
}
