// Generated by delombok at Tue Jun 02 07:45:17 PET 2026
package com.GAKOM_ECOTACNA.ECOTACNA.dto;

import com.GAKOM_ECOTACNA.ECOTACNA.model.SubscriptionStatus;
import java.time.LocalDate;

public class SubscriptionResponse {
    private Long id;
    private Long planId;
    private String planName;
    private SubscriptionStatus status;
    private LocalDate startDate;
    private LocalDate trialEndsAt;
    private LocalDate nextBillingDate;

    @java.lang.SuppressWarnings("all")
    SubscriptionResponse(final Long id, final Long planId, final String planName, final SubscriptionStatus status, final LocalDate startDate, final LocalDate trialEndsAt, final LocalDate nextBillingDate) {
        this.id = id;
        this.planId = planId;
        this.planName = planName;
        this.status = status;
        this.startDate = startDate;
        this.trialEndsAt = trialEndsAt;
        this.nextBillingDate = nextBillingDate;
    }


    @java.lang.SuppressWarnings("all")
    public static class SubscriptionResponseBuilder {
        @java.lang.SuppressWarnings("all")
        private Long id;
        @java.lang.SuppressWarnings("all")
        private Long planId;
        @java.lang.SuppressWarnings("all")
        private String planName;
        @java.lang.SuppressWarnings("all")
        private SubscriptionStatus status;
        @java.lang.SuppressWarnings("all")
        private LocalDate startDate;
        @java.lang.SuppressWarnings("all")
        private LocalDate trialEndsAt;
        @java.lang.SuppressWarnings("all")
        private LocalDate nextBillingDate;

        @java.lang.SuppressWarnings("all")
        SubscriptionResponseBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SubscriptionResponse.SubscriptionResponseBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SubscriptionResponse.SubscriptionResponseBuilder planId(final Long planId) {
            this.planId = planId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SubscriptionResponse.SubscriptionResponseBuilder planName(final String planName) {
            this.planName = planName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SubscriptionResponse.SubscriptionResponseBuilder status(final SubscriptionStatus status) {
            this.status = status;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SubscriptionResponse.SubscriptionResponseBuilder startDate(final LocalDate startDate) {
            this.startDate = startDate;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SubscriptionResponse.SubscriptionResponseBuilder trialEndsAt(final LocalDate trialEndsAt) {
            this.trialEndsAt = trialEndsAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SubscriptionResponse.SubscriptionResponseBuilder nextBillingDate(final LocalDate nextBillingDate) {
            this.nextBillingDate = nextBillingDate;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public SubscriptionResponse build() {
            return new SubscriptionResponse(this.id, this.planId, this.planName, this.status, this.startDate, this.trialEndsAt, this.nextBillingDate);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "SubscriptionResponse.SubscriptionResponseBuilder(id=" + this.id + ", planId=" + this.planId + ", planName=" + this.planName + ", status=" + this.status + ", startDate=" + this.startDate + ", trialEndsAt=" + this.trialEndsAt + ", nextBillingDate=" + this.nextBillingDate + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static SubscriptionResponse.SubscriptionResponseBuilder builder() {
        return new SubscriptionResponse.SubscriptionResponseBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public Long getPlanId() {
        return this.planId;
    }

    @java.lang.SuppressWarnings("all")
    public String getPlanName() {
        return this.planName;
    }

    @java.lang.SuppressWarnings("all")
    public SubscriptionStatus getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDate getStartDate() {
        return this.startDate;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDate getTrialEndsAt() {
        return this.trialEndsAt;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDate getNextBillingDate() {
        return this.nextBillingDate;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setPlanId(final Long planId) {
        this.planId = planId;
    }

    @java.lang.SuppressWarnings("all")
    public void setPlanName(final String planName) {
        this.planName = planName;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatus(final SubscriptionStatus status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    public void setStartDate(final LocalDate startDate) {
        this.startDate = startDate;
    }

    @java.lang.SuppressWarnings("all")
    public void setTrialEndsAt(final LocalDate trialEndsAt) {
        this.trialEndsAt = trialEndsAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setNextBillingDate(final LocalDate nextBillingDate) {
        this.nextBillingDate = nextBillingDate;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof SubscriptionResponse)) return false;
        final SubscriptionResponse other = (SubscriptionResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$planId = this.getPlanId();
        final java.lang.Object other$planId = other.getPlanId();
        if (this$planId == null ? other$planId != null : !this$planId.equals(other$planId)) return false;
        final java.lang.Object this$planName = this.getPlanName();
        final java.lang.Object other$planName = other.getPlanName();
        if (this$planName == null ? other$planName != null : !this$planName.equals(other$planName)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$startDate = this.getStartDate();
        final java.lang.Object other$startDate = other.getStartDate();
        if (this$startDate == null ? other$startDate != null : !this$startDate.equals(other$startDate)) return false;
        final java.lang.Object this$trialEndsAt = this.getTrialEndsAt();
        final java.lang.Object other$trialEndsAt = other.getTrialEndsAt();
        if (this$trialEndsAt == null ? other$trialEndsAt != null : !this$trialEndsAt.equals(other$trialEndsAt)) return false;
        final java.lang.Object this$nextBillingDate = this.getNextBillingDate();
        final java.lang.Object other$nextBillingDate = other.getNextBillingDate();
        if (this$nextBillingDate == null ? other$nextBillingDate != null : !this$nextBillingDate.equals(other$nextBillingDate)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof SubscriptionResponse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $planId = this.getPlanId();
        result = result * PRIME + ($planId == null ? 43 : $planId.hashCode());
        final java.lang.Object $planName = this.getPlanName();
        result = result * PRIME + ($planName == null ? 43 : $planName.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $startDate = this.getStartDate();
        result = result * PRIME + ($startDate == null ? 43 : $startDate.hashCode());
        final java.lang.Object $trialEndsAt = this.getTrialEndsAt();
        result = result * PRIME + ($trialEndsAt == null ? 43 : $trialEndsAt.hashCode());
        final java.lang.Object $nextBillingDate = this.getNextBillingDate();
        result = result * PRIME + ($nextBillingDate == null ? 43 : $nextBillingDate.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "SubscriptionResponse(id=" + this.getId() + ", planId=" + this.getPlanId() + ", planName=" + this.getPlanName() + ", status=" + this.getStatus() + ", startDate=" + this.getStartDate() + ", trialEndsAt=" + this.getTrialEndsAt() + ", nextBillingDate=" + this.getNextBillingDate() + ")";
    }
}
