// Generated by delombok at Tue Jun 02 07:45:17 PET 2026
package com.GAKOM_ECOTACNA.ECOTACNA.dto;

import com.GAKOM_ECOTACNA.ECOTACNA.model.SubscriptionStatus;
import jakarta.validation.constraints.NotNull;

public class SubscriptionRequest {
    @NotNull(message = "subscriptionStatus es obligatorio")
    private SubscriptionStatus subscriptionStatus;

    @java.lang.SuppressWarnings("all")
    public SubscriptionRequest() {
    }

    @java.lang.SuppressWarnings("all")
    public SubscriptionStatus getSubscriptionStatus() {
        return this.subscriptionStatus;
    }

    @java.lang.SuppressWarnings("all")
    public void setSubscriptionStatus(final SubscriptionStatus subscriptionStatus) {
        this.subscriptionStatus = subscriptionStatus;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof SubscriptionRequest)) return false;
        final SubscriptionRequest other = (SubscriptionRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$subscriptionStatus = this.getSubscriptionStatus();
        final java.lang.Object other$subscriptionStatus = other.getSubscriptionStatus();
        if (this$subscriptionStatus == null ? other$subscriptionStatus != null : !this$subscriptionStatus.equals(other$subscriptionStatus)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof SubscriptionRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $subscriptionStatus = this.getSubscriptionStatus();
        result = result * PRIME + ($subscriptionStatus == null ? 43 : $subscriptionStatus.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "SubscriptionRequest(subscriptionStatus=" + this.getSubscriptionStatus() + ")";
    }
}
