// Generated by delombok at Tue Jun 02 07:45:17 PET 2026
package com.GAKOM_ECOTACNA.ECOTACNA.dto;

import jakarta.validation.constraints.NotNull;

public class SubscriptionStartRequest {
    @NotNull
    private Long planId;

    @java.lang.SuppressWarnings("all")
    public SubscriptionStartRequest() {
    }

    @java.lang.SuppressWarnings("all")
    public Long getPlanId() {
        return this.planId;
    }

    @java.lang.SuppressWarnings("all")
    public void setPlanId(final Long planId) {
        this.planId = planId;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof SubscriptionStartRequest)) return false;
        final SubscriptionStartRequest other = (SubscriptionStartRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$planId = this.getPlanId();
        final java.lang.Object other$planId = other.getPlanId();
        if (this$planId == null ? other$planId != null : !this$planId.equals(other$planId)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof SubscriptionStartRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $planId = this.getPlanId();
        result = result * PRIME + ($planId == null ? 43 : $planId.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "SubscriptionStartRequest(planId=" + this.getPlanId() + ")";
    }
}
