// Generated by delombok at Tue Jun 02 07:45:17 PET 2026
package com.GAKOM_ECOTACNA.ECOTACNA.dto;

import com.GAKOM_ECOTACNA.ECOTACNA.model.CompanyType;
import com.GAKOM_ECOTACNA.ECOTACNA.model.SubscriptionStatus;
import java.math.BigDecimal;
import java.time.LocalDate;

public class SubscriptionStatusResponse {
    private String companyName;
    private CompanyType companyType;
    private SubscriptionStatus status;
    private String planName;
    private BigDecimal monthlyAmount;
    private String currency;
    private LocalDate trialEndsAt;
    private LocalDate currentPeriodEnd;
    private Boolean canOperate;
    private String message;

    @java.lang.SuppressWarnings("all")
    SubscriptionStatusResponse(final String companyName, final CompanyType companyType, final SubscriptionStatus status, final String planName, final BigDecimal monthlyAmount, final String currency, final LocalDate trialEndsAt, final LocalDate currentPeriodEnd, final Boolean canOperate, final String message) {
        this.companyName = companyName;
        this.companyType = companyType;
        this.status = status;
        this.planName = planName;
        this.monthlyAmount = monthlyAmount;
        this.currency = currency;
        this.trialEndsAt = trialEndsAt;
        this.currentPeriodEnd = currentPeriodEnd;
        this.canOperate = canOperate;
        this.message = message;
    }


    @java.lang.SuppressWarnings("all")
    public static class SubscriptionStatusResponseBuilder {
        @java.lang.SuppressWarnings("all")
        private String companyName;
        @java.lang.SuppressWarnings("all")
        private CompanyType companyType;
        @java.lang.SuppressWarnings("all")
        private SubscriptionStatus status;
        @java.lang.SuppressWarnings("all")
        private String planName;
        @java.lang.SuppressWarnings("all")
        private BigDecimal monthlyAmount;
        @java.lang.SuppressWarnings("all")
        private String currency;
        @java.lang.SuppressWarnings("all")
        private LocalDate trialEndsAt;
        @java.lang.SuppressWarnings("all")
        private LocalDate currentPeriodEnd;
        @java.lang.SuppressWarnings("all")
        private Boolean canOperate;
        @java.lang.SuppressWarnings("all")
        private String message;

        @java.lang.SuppressWarnings("all")
        SubscriptionStatusResponseBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SubscriptionStatusResponse.SubscriptionStatusResponseBuilder companyName(final String companyName) {
            this.companyName = companyName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SubscriptionStatusResponse.SubscriptionStatusResponseBuilder companyType(final CompanyType companyType) {
            this.companyType = companyType;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SubscriptionStatusResponse.SubscriptionStatusResponseBuilder status(final SubscriptionStatus status) {
            this.status = status;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SubscriptionStatusResponse.SubscriptionStatusResponseBuilder planName(final String planName) {
            this.planName = planName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SubscriptionStatusResponse.SubscriptionStatusResponseBuilder monthlyAmount(final BigDecimal monthlyAmount) {
            this.monthlyAmount = monthlyAmount;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SubscriptionStatusResponse.SubscriptionStatusResponseBuilder currency(final String currency) {
            this.currency = currency;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SubscriptionStatusResponse.SubscriptionStatusResponseBuilder trialEndsAt(final LocalDate trialEndsAt) {
            this.trialEndsAt = trialEndsAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SubscriptionStatusResponse.SubscriptionStatusResponseBuilder currentPeriodEnd(final LocalDate currentPeriodEnd) {
            this.currentPeriodEnd = currentPeriodEnd;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SubscriptionStatusResponse.SubscriptionStatusResponseBuilder canOperate(final Boolean canOperate) {
            this.canOperate = canOperate;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SubscriptionStatusResponse.SubscriptionStatusResponseBuilder message(final String message) {
            this.message = message;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public SubscriptionStatusResponse build() {
            return new SubscriptionStatusResponse(this.companyName, this.companyType, this.status, this.planName, this.monthlyAmount, this.currency, this.trialEndsAt, this.currentPeriodEnd, this.canOperate, this.message);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "SubscriptionStatusResponse.SubscriptionStatusResponseBuilder(companyName=" + this.companyName + ", companyType=" + this.companyType + ", status=" + this.status + ", planName=" + this.planName + ", monthlyAmount=" + this.monthlyAmount + ", currency=" + this.currency + ", trialEndsAt=" + this.trialEndsAt + ", currentPeriodEnd=" + this.currentPeriodEnd + ", canOperate=" + this.canOperate + ", message=" + this.message + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static SubscriptionStatusResponse.SubscriptionStatusResponseBuilder builder() {
        return new SubscriptionStatusResponse.SubscriptionStatusResponseBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public String getCompanyName() {
        return this.companyName;
    }

    @java.lang.SuppressWarnings("all")
    public CompanyType getCompanyType() {
        return this.companyType;
    }

    @java.lang.SuppressWarnings("all")
    public SubscriptionStatus getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    public String getPlanName() {
        return this.planName;
    }

    @java.lang.SuppressWarnings("all")
    public BigDecimal getMonthlyAmount() {
        return this.monthlyAmount;
    }

    @java.lang.SuppressWarnings("all")
    public String getCurrency() {
        return this.currency;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDate getTrialEndsAt() {
        return this.trialEndsAt;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDate getCurrentPeriodEnd() {
        return this.currentPeriodEnd;
    }

    @java.lang.SuppressWarnings("all")
    public Boolean getCanOperate() {
        return this.canOperate;
    }

    @java.lang.SuppressWarnings("all")
    public String getMessage() {
        return this.message;
    }

    @java.lang.SuppressWarnings("all")
    public void setCompanyName(final String companyName) {
        this.companyName = companyName;
    }

    @java.lang.SuppressWarnings("all")
    public void setCompanyType(final CompanyType companyType) {
        this.companyType = companyType;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatus(final SubscriptionStatus status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    public void setPlanName(final String planName) {
        this.planName = planName;
    }

    @java.lang.SuppressWarnings("all")
    public void setMonthlyAmount(final BigDecimal monthlyAmount) {
        this.monthlyAmount = monthlyAmount;
    }

    @java.lang.SuppressWarnings("all")
    public void setCurrency(final String currency) {
        this.currency = currency;
    }

    @java.lang.SuppressWarnings("all")
    public void setTrialEndsAt(final LocalDate trialEndsAt) {
        this.trialEndsAt = trialEndsAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setCurrentPeriodEnd(final LocalDate currentPeriodEnd) {
        this.currentPeriodEnd = currentPeriodEnd;
    }

    @java.lang.SuppressWarnings("all")
    public void setCanOperate(final Boolean canOperate) {
        this.canOperate = canOperate;
    }

    @java.lang.SuppressWarnings("all")
    public void setMessage(final String message) {
        this.message = message;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof SubscriptionStatusResponse)) return false;
        final SubscriptionStatusResponse other = (SubscriptionStatusResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$canOperate = this.getCanOperate();
        final java.lang.Object other$canOperate = other.getCanOperate();
        if (this$canOperate == null ? other$canOperate != null : !this$canOperate.equals(other$canOperate)) return false;
        final java.lang.Object this$companyName = this.getCompanyName();
        final java.lang.Object other$companyName = other.getCompanyName();
        if (this$companyName == null ? other$companyName != null : !this$companyName.equals(other$companyName)) return false;
        final java.lang.Object this$companyType = this.getCompanyType();
        final java.lang.Object other$companyType = other.getCompanyType();
        if (this$companyType == null ? other$companyType != null : !this$companyType.equals(other$companyType)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$planName = this.getPlanName();
        final java.lang.Object other$planName = other.getPlanName();
        if (this$planName == null ? other$planName != null : !this$planName.equals(other$planName)) return false;
        final java.lang.Object this$monthlyAmount = this.getMonthlyAmount();
        final java.lang.Object other$monthlyAmount = other.getMonthlyAmount();
        if (this$monthlyAmount == null ? other$monthlyAmount != null : !this$monthlyAmount.equals(other$monthlyAmount)) return false;
        final java.lang.Object this$currency = this.getCurrency();
        final java.lang.Object other$currency = other.getCurrency();
        if (this$currency == null ? other$currency != null : !this$currency.equals(other$currency)) return false;
        final java.lang.Object this$trialEndsAt = this.getTrialEndsAt();
        final java.lang.Object other$trialEndsAt = other.getTrialEndsAt();
        if (this$trialEndsAt == null ? other$trialEndsAt != null : !this$trialEndsAt.equals(other$trialEndsAt)) return false;
        final java.lang.Object this$currentPeriodEnd = this.getCurrentPeriodEnd();
        final java.lang.Object other$currentPeriodEnd = other.getCurrentPeriodEnd();
        if (this$currentPeriodEnd == null ? other$currentPeriodEnd != null : !this$currentPeriodEnd.equals(other$currentPeriodEnd)) return false;
        final java.lang.Object this$message = this.getMessage();
        final java.lang.Object other$message = other.getMessage();
        if (this$message == null ? other$message != null : !this$message.equals(other$message)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof SubscriptionStatusResponse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $canOperate = this.getCanOperate();
        result = result * PRIME + ($canOperate == null ? 43 : $canOperate.hashCode());
        final java.lang.Object $companyName = this.getCompanyName();
        result = result * PRIME + ($companyName == null ? 43 : $companyName.hashCode());
        final java.lang.Object $companyType = this.getCompanyType();
        result = result * PRIME + ($companyType == null ? 43 : $companyType.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $planName = this.getPlanName();
        result = result * PRIME + ($planName == null ? 43 : $planName.hashCode());
        final java.lang.Object $monthlyAmount = this.getMonthlyAmount();
        result = result * PRIME + ($monthlyAmount == null ? 43 : $monthlyAmount.hashCode());
        final java.lang.Object $currency = this.getCurrency();
        result = result * PRIME + ($currency == null ? 43 : $currency.hashCode());
        final java.lang.Object $trialEndsAt = this.getTrialEndsAt();
        result = result * PRIME + ($trialEndsAt == null ? 43 : $trialEndsAt.hashCode());
        final java.lang.Object $currentPeriodEnd = this.getCurrentPeriodEnd();
        result = result * PRIME + ($currentPeriodEnd == null ? 43 : $currentPeriodEnd.hashCode());
        final java.lang.Object $message = this.getMessage();
        result = result * PRIME + ($message == null ? 43 : $message.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "SubscriptionStatusResponse(companyName=" + this.getCompanyName() + ", companyType=" + this.getCompanyType() + ", status=" + this.getStatus() + ", planName=" + this.getPlanName() + ", monthlyAmount=" + this.getMonthlyAmount() + ", currency=" + this.getCurrency() + ", trialEndsAt=" + this.getTrialEndsAt() + ", currentPeriodEnd=" + this.getCurrentPeriodEnd() + ", canOperate=" + this.getCanOperate() + ", message=" + this.getMessage() + ")";
    }
}
