// Generated by delombok at Tue Jun 02 07:45:17 PET 2026
package com.GAKOM_ECOTACNA.ECOTACNA.dto;

import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import java.math.BigDecimal;

public class TransportUnitRequest {
    private Long empresaRecolectoraId;
    @NotBlank(message = "La placa es obligatoria")
    private String placa;
    private String marca;
    private String modelo;
    @NotNull(message = "capacidadLitros es obligatorio")
    @DecimalMin(value = "0.01", message = "La capacidad debe ser mayor a 0")
    private BigDecimal capacidadLitros;
    private String tipoUnidad;
    private String estado;
    private String observaciones;

    @java.lang.SuppressWarnings("all")
    public TransportUnitRequest() {
    }

    @java.lang.SuppressWarnings("all")
    public Long getEmpresaRecolectoraId() {
        return this.empresaRecolectoraId;
    }

    @java.lang.SuppressWarnings("all")
    public String getPlaca() {
        return this.placa;
    }

    @java.lang.SuppressWarnings("all")
    public String getMarca() {
        return this.marca;
    }

    @java.lang.SuppressWarnings("all")
    public String getModelo() {
        return this.modelo;
    }

    @java.lang.SuppressWarnings("all")
    public BigDecimal getCapacidadLitros() {
        return this.capacidadLitros;
    }

    @java.lang.SuppressWarnings("all")
    public String getTipoUnidad() {
        return this.tipoUnidad;
    }

    @java.lang.SuppressWarnings("all")
    public String getEstado() {
        return this.estado;
    }

    @java.lang.SuppressWarnings("all")
    public String getObservaciones() {
        return this.observaciones;
    }

    @java.lang.SuppressWarnings("all")
    public void setEmpresaRecolectoraId(final Long empresaRecolectoraId) {
        this.empresaRecolectoraId = empresaRecolectoraId;
    }

    @java.lang.SuppressWarnings("all")
    public void setPlaca(final String placa) {
        this.placa = placa;
    }

    @java.lang.SuppressWarnings("all")
    public void setMarca(final String marca) {
        this.marca = marca;
    }

    @java.lang.SuppressWarnings("all")
    public void setModelo(final String modelo) {
        this.modelo = modelo;
    }

    @java.lang.SuppressWarnings("all")
    public void setCapacidadLitros(final BigDecimal capacidadLitros) {
        this.capacidadLitros = capacidadLitros;
    }

    @java.lang.SuppressWarnings("all")
    public void setTipoUnidad(final String tipoUnidad) {
        this.tipoUnidad = tipoUnidad;
    }

    @java.lang.SuppressWarnings("all")
    public void setEstado(final String estado) {
        this.estado = estado;
    }

    @java.lang.SuppressWarnings("all")
    public void setObservaciones(final String observaciones) {
        this.observaciones = observaciones;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof TransportUnitRequest)) return false;
        final TransportUnitRequest other = (TransportUnitRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$empresaRecolectoraId = this.getEmpresaRecolectoraId();
        final java.lang.Object other$empresaRecolectoraId = other.getEmpresaRecolectoraId();
        if (this$empresaRecolectoraId == null ? other$empresaRecolectoraId != null : !this$empresaRecolectoraId.equals(other$empresaRecolectoraId)) return false;
        final java.lang.Object this$placa = this.getPlaca();
        final java.lang.Object other$placa = other.getPlaca();
        if (this$placa == null ? other$placa != null : !this$placa.equals(other$placa)) return false;
        final java.lang.Object this$marca = this.getMarca();
        final java.lang.Object other$marca = other.getMarca();
        if (this$marca == null ? other$marca != null : !this$marca.equals(other$marca)) return false;
        final java.lang.Object this$modelo = this.getModelo();
        final java.lang.Object other$modelo = other.getModelo();
        if (this$modelo == null ? other$modelo != null : !this$modelo.equals(other$modelo)) return false;
        final java.lang.Object this$capacidadLitros = this.getCapacidadLitros();
        final java.lang.Object other$capacidadLitros = other.getCapacidadLitros();
        if (this$capacidadLitros == null ? other$capacidadLitros != null : !this$capacidadLitros.equals(other$capacidadLitros)) return false;
        final java.lang.Object this$tipoUnidad = this.getTipoUnidad();
        final java.lang.Object other$tipoUnidad = other.getTipoUnidad();
        if (this$tipoUnidad == null ? other$tipoUnidad != null : !this$tipoUnidad.equals(other$tipoUnidad)) return false;
        final java.lang.Object this$estado = this.getEstado();
        final java.lang.Object other$estado = other.getEstado();
        if (this$estado == null ? other$estado != null : !this$estado.equals(other$estado)) return false;
        final java.lang.Object this$observaciones = this.getObservaciones();
        final java.lang.Object other$observaciones = other.getObservaciones();
        if (this$observaciones == null ? other$observaciones != null : !this$observaciones.equals(other$observaciones)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof TransportUnitRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $empresaRecolectoraId = this.getEmpresaRecolectoraId();
        result = result * PRIME + ($empresaRecolectoraId == null ? 43 : $empresaRecolectoraId.hashCode());
        final java.lang.Object $placa = this.getPlaca();
        result = result * PRIME + ($placa == null ? 43 : $placa.hashCode());
        final java.lang.Object $marca = this.getMarca();
        result = result * PRIME + ($marca == null ? 43 : $marca.hashCode());
        final java.lang.Object $modelo = this.getModelo();
        result = result * PRIME + ($modelo == null ? 43 : $modelo.hashCode());
        final java.lang.Object $capacidadLitros = this.getCapacidadLitros();
        result = result * PRIME + ($capacidadLitros == null ? 43 : $capacidadLitros.hashCode());
        final java.lang.Object $tipoUnidad = this.getTipoUnidad();
        result = result * PRIME + ($tipoUnidad == null ? 43 : $tipoUnidad.hashCode());
        final java.lang.Object $estado = this.getEstado();
        result = result * PRIME + ($estado == null ? 43 : $estado.hashCode());
        final java.lang.Object $observaciones = this.getObservaciones();
        result = result * PRIME + ($observaciones == null ? 43 : $observaciones.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "TransportUnitRequest(empresaRecolectoraId=" + this.getEmpresaRecolectoraId() + ", placa=" + this.getPlaca() + ", marca=" + this.getMarca() + ", modelo=" + this.getModelo() + ", capacidadLitros=" + this.getCapacidadLitros() + ", tipoUnidad=" + this.getTipoUnidad() + ", estado=" + this.getEstado() + ", observaciones=" + this.getObservaciones() + ")";
    }
}
